### ISSUE TITLE
com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/wordlist/english.txt'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1062]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.load_wordlist(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/mnemonic.py:93)
	at <python>.__init__(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/mnemonic.py:125)
	at <python>.make_seed(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/commands.py:207)
	at <python>.func_wrapper(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/commands.py:100)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:274)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:246)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:140)
	at org.electroncash.electroncash3.NewWalletDialog1$onShowDialog$1.onClick(Wallets.kt:210)
	at android.view.View.performClick(View.java:5697)
	at android.widget.TextView.performClick(TextView.java:10814)
	at android.view.View$PerformClick.run(View.java:22526)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/wordlist/english.txt'
```

Reporter
------------

This issue was reported by 5 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.2-6  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 6.0.1 on samsung SM-G935F (hero2lte) | unknown | en_GB | 
| 3.3.2-6  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.1.1 on OPPO CPH1717 (CPH1717) | unknown | en_US | 
| 3.3.2-6  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.1.1 on OPPO CPH1717 (CPH1717) | unknown | en_US | 
| 3.3.2-6  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.1.1 on OPPO CPH1717 (CPH1717) | unknown | en_US | 
| 3.3.2-6  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.1.1 on OPPO CPH1717 (CPH1717) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by liyanhrxy** [comment]
![image](https://user-images.githubusercontent.com/32901980/70713617-5e36d700-1d21-11ea-8b46-f96048857a2b.png)
how to resolve error like this ? the file was really exists !!!
