### ISSUE TITLE
com.chaquo.python.PyException: OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1096]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>._check_connected(stdlib/ssl.py:861)
	at <python>.getpeercert(stdlib/ssl.py:897)
	at <python>.get_socket(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/interface.py:155)
	at <python>.run(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/interface.py:240)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash_gui/android/daemon.py:34)
	at <python>.reraise(/android_asset/chaquopy/requirements-common.zip/six.py:693)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash_gui/android/daemon.py:25)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:274)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:246)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
	at $Proxy4.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
com.chaquo.python.PyException: OSError: [Errno 107] Transport endpoint is not connected
```

Reporter
------------

This issue was reported by 4 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.4-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.0.0 on samsung SM-G960F (starlte) | unknown | sv_SE | 
| 3.3.4-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.0.0 on samsung SM-N950W (greatqltecs) | unknown | en_CA | 
| 3.3.2-6  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.1.1 on LGE LG-US601 (mlv7) | unknown | en_US | 
| 3.3.4-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.0.0 on samsung SM-G935F (hero2lte) | unknown | de_DE | 

Additional Information
------------------------

> I have no clue

---

**Comment by mhsmith** [comment]
I haven't changed anything in this area. Is it possible that this is happening on other platforms, but they're not notifying the crash reporter because they're crashing in a background thread?

**Comment by mhsmith** [comment]
If I understand correctly, this isn't the main network thread, but a temporary per-socket thread which only exists during the connection process. And it looks like any netwoek error is supposed to just be caught and logged, and the network thread notified that the connection failed. 

I guess this is another case of network errors appearing with a different exception type on Android, like in #994. Half of `get_socket` is already covered by an `except BaseException` handler, so if you agree, I'll just extend that to include the whole function.

**Comment by mhsmith** [comment]
Actually, in Python 3 all network exceptions are subclasses of `OSError`, so I'll catch that instead. Any other exception classes would indicate a definite programming error and should still trigger the crash reporter.
