### ISSUE TITLE
Cannot start daemon in testnet mode

### ISSUE THREAD

**Issue by leevlad** [Electron-Cash/Electron-Cash#1120]
**Electron Cash Version**: `3.3.4`
**Platform**: `MacOS Mojave 10.14.3 (18D42)`

# Observed Behaviour
When using the command line to launch the daemon in testnet mode, a crash occurs. See below:

```bash
$ /Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash daemon start --testnet

Traceback (most recent call last):
  File "electron-cash", line 411, in <module>
  File "jsonrpclib/jsonrpc.py", line 650, in __call__
  File "jsonrpclib/jsonrpc.py", line 532, in _request
  File "jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
jsonrpclib.jsonrpc.ProtocolError: (-32601, 'Method daemon not supported.')
[8196] Failed to execute script electron-cash
```

Note that the daemon starts without the `--testnet` param.

**Comment by marceloneil** [comment]
I seem to recall it was
```shell
electron-cash daemon --testnet start
```
Maybe try that?

**Comment by leevlad** [comment]
Thanks for the suggestion. That doesn't seem to work either, and throws the same exception.

**Comment by cculianu** [comment]
It looks like it thinks you're already running a daemon or something.  This definitely works for me here on MacOS latest release as well as git head.  Make sure no daemons are already running.  It seems confused.

Also try latest git head.

Let me know!

**Comment by leevlad** [comment]
Thanks for the reply. I am indeed running the UI already. I was expecting this to spawn a new daemon as the `bch daemon status` command returned `Daemon not running`.

Looks like killing the UI solved it for me. 

I suppose the only suggested improvement at this point is to clean up the error message there. If the UI is running, starting the daemon should say `Daemon already running`.

**Comment by cculianu** [comment]
Ok yeah Jonald told me tomorrow.. so.. pretty sure we're doing it then.  👍
