### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by pexmull** [Electron-Cash/Electron-Cash#1138]
Got the following error while compiling for windows. I ran "build.sh"

```
Using c:\python3.5.4\lib\site-packages
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using c:\python3.5.4\lib\site-packages
Finished processing dependencies for Electron-Cash==3.3.5
/home/Electron-Cash/contrib/build-wine/tmp
622 INFO: PyInstaller: 3.4.dev0+879570913
623 INFO: Python: 3.5.4
632 INFO: Platform: Windows-XP-5.1.2600
645 INFO: UPX is not available.
Traceback (most recent call last):
  File "C:\python3.5.4\scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0', 'console_scripts', 'pyinstaller')()
  File "c:\python3.5.4\lib\site-packages\PyInstaller\__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python3.5.4\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python3.5.4\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python3.5.4\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 62, in <module>
  File "c:\python3.5.4\lib\site-packages\PyInstaller\building\build_main.py", line 162, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script 'C:\electrum\plugins\trezor\client.py' not found
```

**Comment by cculianu** [comment]
Weird. It shouldn't be looking for plugins/trezor/client.py  -- that file was removed from this codebase.

Are you off latest sources or .. what?

**Comment by doremon1** [comment]
mybad. :(

**Comment by cculianu** [comment]
Just curious -- what was the problem?
