### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 127507052 byte allocation with 4194256 free bytes and 43MB until OOM

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1166]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:663)
	at android.widget.Editor$TextMagnifierView.createMag(Editor.java:1445)
	at android.widget.Editor$TextMagnifierView.show(Editor.java:1501)
	at android.widget.Editor.magnifierAndDtrag(Editor.java:1273)
	at android.widget.Editor.performLongClick(Editor.java:1251)
	at android.widget.TextView.performLongClick(TextView.java:9868)
	at android.view.View.performLongClick(View.java:5728)
	at android.view.View$CheckForLongPress.run(View.java:22610)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
java.lang.OutOfMemoryError: Failed to allocate a 127507052 byte allocation with 4194256 free bytes and 43MB until OOM
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.0 on WIKO Lenny4 Plus (v3740) | unknown | th_TH | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
Any ideas @mhsmith?

**Comment by mhsmith** [comment]
No idea, doesn't seem to be anything under our control. And there aren't even any Google results for `TextMagnifierView`, so maybe it's running some modified version of Android. 

[This](https://developer.android.com/guide/topics/text/magnifier) is something similar, but it's a different class name and it's only available starting from Android 9, so I don't think it's related.

**Comment by cculianu** [comment]
Wow.. bizarro.  Ok, closing and marking invalid.

**Comment by fty48jj19** [comment]
e   bom a muito pobremas antigo que achei aqui  enrregular  aplicativo  antigos  muitas long errado nos estamos 2019  vc es ainda esta em 2018  ai esta o saite para vc se enforma acredito q vc sabe ler nao e burro  nome do saite  para vc fazer revisao no diratorio de senha codigo so vc ler nova direçao das modificança  talves vc tenha que mudar sua visao para fomalizar  situaçao  ver o que esta fazendo  vc nao esta mas na versao antiga nao vamos mudar vamos procura se atualizar  se vc nao sabe alguma coisa pergunta alguem vai enfrente eu amigo nao sou jesus para resolver o mundo todo nao  posso tenta te ajudar  se minha colcaçao para vc esta cendo rui vamo tenta milhora estou aqui para te ajuda um abraço amigo vou mim esforça para ver tudo organizando ok,

**Comment by cculianu** [comment]
How do we ban this guy? He's been spamming our github here with this gibberish.

**Comment by fty48jj19** [comment]
e  amigo estou tentano faze da melhor forma para vc para outra pessoas se falha nao sou eu nao tenta animinizar alguma coisas  vc pode visita o sait   q mim ajuda  colabora com vcs  ele pode solicita chaves diretoria de senhas codigos e fazer uma nova solicitaçao talves vc esteja usando chaves misturadas com antiga etc..

**Comment by ProfessorVenkman** [comment]
Good evening @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.5-5.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 3.3.5-1 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:755)
	at org.electroncash.electroncash3.QRKt.showQRNow(QR.kt:57)
	at org.electroncash.electroncash3.QRKt.access$showQRNow(QR.kt:1)
	at org.electroncash.electroncash3.QRKt$showQR$listener$1.onLayoutChange(QR.kt:30)
	at android.view.View.layout(View.java:18808)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.widget.ScrollView.onLayout(ScrollView.java:2535)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at androidx.appcompat.widget.AlertDialogLayout.setChildFrame(AlertDialogLayout.java:348)
	at androidx.appcompat.widget.AlertDialogLayout.onLayout(AlertDialogLayout.java:341)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:822)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2634)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2350)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1509)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7051)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
	at android.view.Choreographer.doFrame(Choreographer.java:638)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
java.lang.OutOfMemoryError: Failed to allocate a 1102512 byte allocation with 745096 free bytes and 727KB until OOM
```


~ _With robotic wishes_
