### ISSUE TITLE
Ledger: Retrying after device was not in Bitcoin Cash mode does not work

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#1243]
When you try to use a Ledger that is not in Bitcoin Cash mode that is correctly detected and a message is shown:

```
Traceback (most recent call last):
  File "/home/user/src/electrum/plugins/ledger/ledger.py", line 204, in checkDevice
    self.perform_hw1_preflight()
  File "/home/user/src/electrum/plugins/ledger/ledger.py", line 199, in perform_hw1_preflight
    raise e
  File "/home/user/src/electrum/plugins/ledger/ledger.py", line 149, in perform_hw1_preflight
    firmwareInfo = self.dongleObject.getFirmwareVersion()
  File "/home/user/.local/lib/python3.5/site-packages/btchip/btchip.py", line 561, in getFirmwareVersion
    response = self.dongle.exchange(bytearray(apdu))
  File "/home/user/.local/lib/python3.5/site-packages/btchip/btchipComm.py", line 127, in exchange
    raise BTChipException("Invalid status %04x" % sw, sw)
btchip.btchipException.BTChipException: Exception : Invalid status 6700

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/src/electrum/gui/qt/util.py", line 691, in run
    result = task.task()
  File "/home/user/src/electrum/plugins/ledger/ledger.py", line 549, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/home/user/src/electrum/lib/plugins.py", line 718, in client_for_keystore
    client = self.force_pair_xpub(plugin, handler, info, xpub, derivation, devices)
  File "/home/user/src/electrum/lib/plugins.py", line 748, in force_pair_xpub
    client_xpub = client.get_xpub(derivation, xtype)
  File "/home/user/src/electrum/plugins/ledger/ledger.py", line 78, in catch_exception
    return func(self, *args, **kwargs)
  File "/home/user/src/electrum/plugins/ledger/ledger.py", line 88, in get_xpub
    self.checkDevice()
  File "/home/user/src/electrum/plugins/ledger/ledger.py", line 207, in checkDevice
    raise BaseException(_("Device not in Bitcoin Cash mode")) from e
BaseException: Device not in Bitcoin Cash mode
```

After confirming the dialog and switching the Ledger into Bitcoin Cash mode, the Ledger button does not do anything anymore. It should be possible to just retry the connection and succeed.

**Comment by EchterAgo** [comment]
Looks like I misunderstood something here. The plugin button in the status bar seems to be for opening custom plugin settings, not for retrying the pairing in case it fails in `HW_PluginBase.get_client`. However I do think it is a good place to retry the pairing and achieved this using this code in `QtPluginBase.show_settings_dialog`:

```
if self.device_manager().xpub_by_id(device_id) == None:
            keystore.thread.add(partial(self.get_client, keystore))
```

This seems to work nicely.

I've also found a bug in `plugins.DeviceMgr.scan_devices`. When a device is detected as disconnected but is not present in `xpub_ids`, like in the case of the "Device not in Bitcoin Cash mode" message, the devices `close` function will not be called. For the Ledger this means the devices stays opened.

The reason for this is that in `plugins.DeviceMgr.scan_devices` the `self.clients` variable is reset before the disconnected ids are unpaired. When it tries to unpair the device after that, it will fail because it can not do `client_lookup` by the device id. I've solved this by moving the unpairing before the reset of `self.clients`
