### ISSUE TITLE
electron-cash --testnet daemon start (not working - v3.0)

### ISSUE THREAD

**Issue by malik9353** [Electron-Cash/Electron-Cash#1340]
I have install electroncash-3.0.tar.gz its working fine on mainnet but testnet daemon is not wokring.
**Error is as below :**
```
root@ip-172-31-31-67:/home/ubuntu/Electron Cash-3.0# electron-cash daemon --testnet start
starting daemon (PID 2594)
Traceback (most recent call last):
  File "/usr/local/bin/electron-cash", line 4, in <module>
    __import__('pkg_resources').run_script('Electron-Cash==3.0', 'electron-cash')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Electron_Cash-3.0-py3.6.egg/EGG-INFO/scripts/electron-cash", line 395, in <module>
    d = daemon.Daemon(config, fd)
  File "/usr/local/lib/python3.6/dist-packages/Electron_Cash-3.0-py3.6.egg/electroncash/daemon.py", line 112, in __init__
    self.network = Network(config)
  File "/usr/local/lib/python3.6/dist-packages/Electron_Cash-3.0-py3.6.egg/electroncash/network.py", line 221, in __init__
    self.start_network(deserialize_server(self.default_server)[2],
  File "/usr/local/lib/python3.6/dist-packages/Electron_Cash-3.0-py3.6.egg/electroncash/network.py", line 140, in deserialize_server
    host, port, protocol = str(server_str).split(':')
ValueError: not enough values to unpack (expected 3, got 1)
root@ip-172-31-31-67:/home/ubuntu/Electron Cash-3.0# rm -f ~/.electron-cash/testnet/daemon

```

**Comment by cculianu** [comment]
You should update to latest 4.0.2 release.  We no longer support 3.0.

If you continue to have problems on 4.0.2 release, then feel free to open another issue. I'm closing this for now.
