### ISSUE TITLE
[SLP] [Bug] on_restore_seed() incorrect positional arguments

### ISSUE THREAD

**Issue by Greg-Griffith** [Electron-Cash/Electron-Cash#1343]
__Issue__
when trying to create a new wallet from previously saved seeds, the wallet displays and error and closes

__Version__ 
Electron-Cash-SLP-3.4.11-x86_64.AppImage

__Error__ 
TypeError: on_restore_seed() takes 4 positional arguments but 5 were given

__How to re-create__
1) start electron cash with no wallet file in the wallets folder
2) click next to create SLP wallet 
3) select "standard wallet", click next
4) select "I already have a seed", click next
5) enter the seed (it should say BIP 39 checksum ok), and then click next
6) an error box with the following text is displayed: TypeError: on_restore_seed() takes 4 positional arguments but 5 were given

__Traceback__
```
Traceback (most recent call last):
  File "<tmp path>/python3.6/site-packages/electroncash_gui/qt/__init__.py", line 298, in start_new_window
    wallet = wizard.run_and_get_wallet()

  File "<tmp path>/python3.6/site-packages/electroncash_gui/qt/installwizard.py", line 294, in run_and_get_wallet
    self.run(action)

  File "<tmp path>/python3.6/site-packages/electroncash/base_wizard.py", line 62, in run
    f(*args)

  File "<tmp path>/python3.6/site-packages/electroncash/base_wizard.py", line 88, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)

  File "<tmp path>/python3.6/site-packages/electroncash_gui/qt/installwizard.py", line 92, in func_wrapper
    run_next(*out)

  File "<tmp path>/python3.6/site-packages/electroncash/base_wizard.py", line 98, in on_wallet_type
    self.run(action)

  File "<tmp path>/python3.6/site-packages/electroncash/base_wizard.py", line 62, in run
    f(*args)

  File "<tmp path>/python3.6/site-packages/electroncash/base_wizard.py", line 132, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)

  File "<tmp path>/python3.6/site-packages/electroncash_gui/qt/installwizard.py", line 92, in func_wrapper
    run_next(*out)

  File "<tmp path>/python3.6/site-packages/electroncash/base_wizard.py", line 62, in run
    f(*args)

  File "<tmp path>/python3.6/site-packages/electroncash/base_wizard.py", line 298, in restore_from_seed
    self.restore_seed_dialog(run_next=self.on_restore_seed, test=test)

  File "<tmp path>/python3.6/site-packages/electroncash_gui/qt/installwizard.py", line 92, in func_wrapper
    run_next(*out)

TypeError: on_restore_seed() takes 4 positional arguments but 5 were given

```

let me know if you need more information

**Comment by cculianu** [comment]
Yes. Was a bug. I fixed this in latest git head on simpleledger/Electron-Cash-SLP

**Comment by Greg-Griffith** [comment]
awesome thanks.
