### ISSUE TITLE
com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/org.electroncash.wallet/files/data/wallets/jchillah.tmp.8448' -> '/data/user/0/org.electroncash.wallet/files/data/wallets/jchillah'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1364]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>._write(/android_asset/chaquopy/app.zip/electroncash/storage.py:203)
	at <python>.write(/android_asset/chaquopy/app.zip/electroncash/storage.py:176)
	at <python>.do_profile(/android_asset/chaquopy/app.zip/electroncash/util.py:246)
	at <python>.<lambda>(/android_asset/chaquopy/app.zip/electroncash/util.py:250)
	at <python>.update_password(/android_asset/chaquopy/app.zip/electroncash/wallet.py:1551)
	at <python>.create(/android_asset/chaquopy/app.zip/electroncash_gui/android/console.py:161)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at org.electroncash.electroncash3.DaemonModel.createWallet(Daemon.kt:121)
	at org.electroncash.electroncash3.NewWalletSeedDialog.onCreateWallet(Wallets.kt:280)
	at org.electroncash.electroncash3.NewWalletDialog2$onShowDialog$1$1.run(Wallets.kt:248)
	at java.lang.Thread.run(Thread.java:764)
com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/org.electroncash.wallet/files/data/wallets/jchillah.tmp.8448' -> '/data/user/0/org.electroncash.wallet/files/data/wallets/jchillah'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 9 on Sony G8141 (G8141) | unknown | de_DE | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Can't reproduce or explain. However, I'm going to change `os.rename` to `os.replace` here, which may improve error reporting if it happens again, and will also give us atomic saves on Windows.

**Comment by cculianu** [comment]
Ah, sounds good.  The original programmers likely didn't do this because this started out as a Python 2 app (no os.replace there).  Good call.  It's definitely what we want there and maybe will also reduce those Windows errors. 👍

**Comment by mhsmith** [comment]
Possibly caused by the same threading bug as #1575.
