### ISSUE TITLE
com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/data/user/10/org.electroncash.wallet/files/data/wallets/t2'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1406]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.__init__(/android_asset/chaquopy/app.zip/electroncash/storage.py:76)
	at <python>.load_wallet(/android_asset/chaquopy/app.zip/electroncash_gui/android/console.py:112)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at org.electroncash.electroncash3.DaemonModel.loadWallet(Daemon.kt:127)
	at org.electroncash.electroncash3.OpenWalletDialog.onPassword(Wallets.kt:432)
	at org.electroncash.electroncash3.PasswordDialog$tryPassword$r$1.run(Wallets.kt:396)
	at java.lang.Thread.run(Thread.java:784)
com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/data/user/10/org.electroncash.wallet/files/data/wallets/t2'
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on HUAWEI CLT-L29 (HWCLT) | unknown | nb_NO | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on HUAWEI CLT-L29 (HWCLT) | unknown | nb_NO | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by GhostlikeDMB** [comment]
http://bit.ly/2YXs0XO

**Comment by mhsmith** [comment]
Can't reproduce or explain.

**Comment by cculianu** [comment]
Hmm.. close and if it resurfaces worry then?
