### ISSUE TITLE
tx input fetcher throws exceptions for missing inputs

### ISSUE THREAD

**Issue by markblundeberg** [Electron-Cash/Electron-Cash#1438]
Pretty rare situation, but im_uname noticed this.

Here's a tx with garbage inputs for testing:
```
01000000016e56e3a9051e17a1547e41ea989d38c19f7f083d55a749e836baea6733e9040f0000000064414cb43694432d0f3c355cd644e9196b0e630a9399348c1e351e093063a5c80f9fa356f1b301cbce3a0d5432ba6afcdf6a5f4970dd9c6f7ebaf5944790d974a71e4121037788a839a4243e713728e4b3e7db1b72eb364d01d5eaf2425ad99a187f857977feffffff01ff0f0000000000001976a9143697dfb7d0b30e003f42aa9edbab9f4f4b9f522688acdcf20800
```

Exception
```
Traceback (most recent call last):
  File "/home/mark/git/Electron-Cash/lib/transaction.py", line 1049, in put_in_queue_and_cache
    tx = Transaction(r['result'])
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mark/git/Electron-Cash/lib/util.py", line 730, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/home/mark/git/Electron-Cash/lib/network.py", line 1425, in run
    self.wait_on_sockets()
  File "/home/mark/git/Electron-Cash/lib/network.py", line 1399, in wait_on_sockets
    self.process_responses(interface)
  File "/home/mark/git/Electron-Cash/lib/network.py", line 823, in process_responses
    self.process_response(interface, request, response, callbacks)
  File "/home/mark/git/Electron-Cash/lib/network.py", line 770, in process_response
    callback(response)
  File "/home/mark/git/Electron-Cash/lib/transaction.py", line 1055, in put_in_queue_and_cache
    bad_txids.add(txid)
UnboundLocalError: local variable 'txid' referenced before assignment
```

**Comment by cculianu** [comment]
Yep.  Good catch. Made a small programming error.. this should be handled.  Fixing now.

**Comment by cculianu** [comment]
Thanks for catching this. Oops! FIxed in git head.
