### ISSUE TITLE
"excessive resource usage" in jsonrpc

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1467]
```
Traceback (most recent call last):
  File "/home/nick/bitcoin/electrum/electrum/util.py", line 918, in wrapper
    return await func(*args, **kwargs)
  File "/home/nick/bitcoin/electrum/electrum/interface.py", line 296, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/nick/bitcoin/electrum/electrum/interface.py", line 314, in run
    await self.open_session(ssl_context)
  File "/home/nick/bitcoin/electrum/electrum/interface.py", line 414, in open_session
    await group.spawn(self.monitor_connection)
  File "/usr/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/lib/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/nick/bitcoin/electrum/electrum/interface.py", line 426, in ping
    await self.session.send_request('server.ping')
  File "/home/nick/bitcoin/electrum/electrum/interface.py", line 107, in send_request
    timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/site-packages/aiorpcx/session.py", line 632, in send_request
    return await self._send_concurrent(message, event, 1)
  File "/usr/lib/python3.7/site-packages/aiorpcx/session.py", line 609, in _send_concurrent
    raise result
aiorpcx.jsonrpc.RPCError: (-101, 'excessive resource usage')
```

Doesn't seem to impair any functionality, but still thought I'd drop this here.

This is on recent master branch at commit 8ae6ddcc00115933b45a8b691498d1f707d0b92f

**Comment by molecular** [comment]
sorry, this is electrum ;-)

**Comment by cculianu** [comment]
LOL
