### ISSUE TITLE
Update Checker download times out when connected to a slowish proxy server

### ISSUE THREAD

**Issue by jcramer** [Electron-Cash/Electron-Cash#1509]
```
Traceback (most recent call last):
  File "/Users/jc/Source/Electron-Cash-SLP/gui/qt/update_checker.py", line 322, in run
    self.json, self.url = self._do_request(self.url)
  File "/Users/jc/Source/Electron-Cash-SLP/gui/qt/update_checker.py", line 332, in _do_request
    response = requests.get(url, allow_redirects=True, timeout=5.0) # will raise requests.exceptions.Timeout on timeout
  File "/usr/local/lib/python3.7/site-packages/requests-2.21.0-py3.7.egg/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests-2.21.0-py3.7.egg/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests-2.21.0-py3.7.egg/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests-2.21.0-py3.7.egg/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests-2.21.0-py3.7.egg/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.github.com', port=443): Max retries exceeded with url: /simpleledger/Electron-Cash-SLP/master/contrib/update_checker/releases.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e4a8d68>: Failed to establish a new connection: Socket error: timed out'))
```

**Comment by cculianu** [comment]
Hmm ok, I'm on vacation now but I can fix this when I get back. I can make it just wait with a longer timeout if connected to a proxy..

**Comment by jcramer** [comment]
@cculianu ^

**Comment by cculianu** [comment]
I'll just up the timeout, lol

**Comment by cculianu** [comment]
I just set the timeout from 5.0 seconds (!) to 30.0 seconds.  It runs in a thread and the user can abort it at any time so specifying such a long timeout does no harm and only good.

I'll cherry-pick this over to SLP now...
