### ISSUE TITLE
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: 'electroncash'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1566]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4595)
	at android.app.ActivityThread.access$1500(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5293)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: 'electroncash'
	at <python>._rmtree_safe_fd(stdlib/shutil.py:412)
	at <python>._rmtree_safe_fd(stdlib/shutil.py:414)
	at <python>.rmtree(stdlib/shutil.py:480)
	at <python>.initialize_importlib(/data/data/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:72)
	at <python>.initialize(/data/data/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:40)
	at <python>.initialize(/data/data/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/__init__.py:13)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:130)
	at com.chaquo.python.Python.start(Python.java:51)
	at org.electroncash.electroncash3.DaemonKt$py$2.invoke(Daemon.kt:12)
	at org.electroncash.electroncash3.DaemonKt$py$2.invoke(Daemon.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.electroncash.electroncash3.DaemonKt.getPy(Daemon.kt)
	at org.electroncash.electroncash3.DaemonKt.libMod(Daemon.kt:15)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Network.kt:30)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Network.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.electroncash.electroncash3.NetworkKt.getLibNetwork(Network.kt)
	at org.electroncash.electroncash3.SettingsKt.setDefaultValues(Settings.kt:38)
	at org.electroncash.electroncash3.SettingsKt.initSettings(Settings.kt:23)
	at org.electroncash.electroncash3.App.onCreate(App.kt:47)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4592)
	... 9 more
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: 'electroncash'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.9-0  | java.lang.IllegalStateException: Python startup previously failed, and cannot be retried | Android 5.1.1 on Google google Pixel 2 (x86) | unknown | en_NG | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
Unsupported/private build of app.  Right, @mhsmith?

**Comment by cculianu** [comment]
Oh wait you said you released 4.0.9. I will re-open. Let me know !

**Comment by mhsmith** [comment]
Yes, this one looks real, I'll investigate.

**Comment by mhsmith** [comment]
Possibly another case of cache files being automatically cleared, like in in #1062. If so, it should be fixed by moving to the newest version of Chaquopy, which uses the files directory instead.

**Comment by mhsmith** [comment]
Waiting for @fyookball to build and upload https://github.com/Electron-Cash/chaquopy-ec-source/pull/5.
