### ISSUE TITLE
com.chaquo.python.PyException: ExcessiveFee: 

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1578]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.make_unsigned_transaction(/android_asset/chaquopy/app.zip/electroncash/wallet.py:1282)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at org.electroncash.electroncash3.SendDialog.makeUnsignedTransaction(Send.kt:144)
	at org.electroncash.electroncash3.SendDialog.updateUI(Send.kt:105)
	at org.electroncash.electroncash3.SendDialog$onShowDialog$2.onCheckedChanged(Send.kt:79)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:156)
	at android.widget.ToggleButton.setChecked(ToggleButton.java:71)
	at android.widget.CompoundButton.toggle(CompoundButton.java:115)
	at android.widget.CompoundButton.performClick(CompoundButton.java:120)
	at android.view.View$PerformClick.run(View.java:22455)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
com.chaquo.python.PyException: ExcessiveFee: 
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.8-0  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.1.1 on motorola Moto G Play (harpia) | unknown | en_US | 

Additional Information
------------------------

> when sending max amount

---

**Comment by mhsmith** [comment]
I still don't understand where this 4.0.8 build has come from, but I'll look into this anyway.

**Comment by proteanx** [comment]
You guys can probably close this. I imagine over the last week or so you've received a few weird reports with 4.0.8. I've switched out the crashhub link on our repo where we've been testing our fork. Sorry for the confusion (or any wasted time)!

**Comment by cculianu** [comment]
What fork is that? Link?

**Comment by EchterAgo** [comment]
Probably https://github.com/devaultcrypto/DeLight

**Comment by EchterAgo** [comment]
@proteanx please also change the PyInstaller tag. I made an issue here:

https://github.com/devaultcrypto/DeLight/issues/2
