### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForVertical(int)' on a null object reference

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1592]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at com.chaquo.python.utils.ConsoleActivity.saveScroll(ConsoleActivity.java:198)
	at com.chaquo.python.utils.ConsoleActivity.restoreScroll(ConsoleActivity.java:217)
	at com.chaquo.python.utils.ConsoleActivity.onGlobalLayout(ConsoleActivity.java:161)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:959)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2853)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1853)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8476)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForVertical(int)' on a null object reference
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.9-0  | 3.6.5 (default, Dec  7 2018, 14:03:01)  [GCC 4.9] | Android 9 on samsung SM-G955U1 (dream2qlteue) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Exposed by fix to #1330.
