### ISSUE TITLE
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'x16'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1603]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.<lambda>(<console>:1)
	at <python>.run(stdlib/threading.py:864)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash_gui/android/daemon.py:34)
	at <python>.reraise(/android_asset/chaquopy/requirements-common.zip/six.py:693)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash_gui/android/daemon.py:25)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at $Proxy3.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4745)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'x16'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.10-0  | 3.6.5 (default, Dec  7 2018, 14:06:05)  [GCC 4.9] | Android 4.1.2 on unknown Android SDK built for x86 (generic_x86) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Just me testing crash reports again: please close.
