### ISSUE TITLE
java.lang.IllegalStateException: Failure saving state: ServerPreferenceDialog{51d696d #2 org.electroncash.electroncash3.ServerPreferenceDialog} has target not in fragment manager: SettingsFragment{af349a2}

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1611]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2975)
	at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:134)
	at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:591)
	at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:510)
	at android.app.Activity.performSaveInstanceState(Activity.java:1487)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1318)
	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:5484)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5435)
	at android.app.ActivityThread.access$1200(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1827)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7326)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
java.lang.IllegalStateException: Failure saving state: ServerPreferenceDialog{51d696d #2 org.electroncash.electroncash3.ServerPreferenceDialog} has target not in fragment manager: SettingsFragment{af349a2}
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.9-0  | 3.6.5 (default, Dec  7 2018, 14:03:01)  [GCC 4.9] | Android 6.0.1 on samsung SM-C7000 (c7ltechn) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
To reproduce:
* Open server dialog box
* Rotate screen twice

**Comment by cculianu** [comment]
😢

**Comment by mhsmith** [comment]
I know, the platform makes it so easy to write code that works perfectly until someone rotates the screen. Even after years of experience I still get caught out by this almost every week.
