### ISSUE TITLE
com.chaquo.python.PyException: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 0: invalid start byte

### ISSUE THREAD

**Issue by shuaiLiWang** [Electron-Cash/Electron-Cash#1665]
Caused by: com.chaquo.python.PyException: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 0: invalid start byte
        at <python>.java.chaquopy_android.f1(chaquopy_android_ec.pxi:31)
        at <python>.java.chaquopy_android.AssetFile_get_mgr(chaquopy_android_ec.pxi:14)
        at <python>.java.chaquopy_android.AssetFile.__init__(chaquopy_android.pyx:33)
        at <python>.java.android.importer.__init__(importer.py:426)
        at <python>.java.android.importer.__init__(importer.py:201)
        at <python>.pkgutil.get_importer(pkgutil.py:416)
        at <python>.java.android.importer.initialize_importlib(importer.py:55)
        at <python>.java.android.importer.initialize(importer.py:34)
        at <python>.java.android.initialize(__init__.py:13)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
        at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:128)
        at com.chaquo.python.Python.start(Python.java:51)
        at org.electrum.electrum.AppKt$py$2.invoke(App.kt:25)
        at org.electrum.electrum.AppKt$py$2.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.electrum.electrum.AppKt.getPy(Unknown Source:7)
        at org.electrum.electrum.AppKt.guiMod(App.kt:29)
        at org.electrum.electrum.AppKt$testConsole$2.invoke(App.kt:32)
        at org.electrum.electrum.AppKt$testConsole$2.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.electrum.electrum.AppKt.getTestConsole(Unknown Source:7)
        at org.electrum.electrum.App.onCreate(App.kt:68)
        at android.app.Instrumentation.callApplicationOnCreate(Instrum

**Comment by shuaiLiWang** [comment]
Android 9 on Xiaomi MI CC9

**Comment by mhsmith** [comment]
From https://github.com/spesmilo/electrum/issues/5756.

It looks like you're trying to use the Electron Cash Chaquopy builds with another app. Those builds are licensed only to Electron Cash. If your project would like to discuss a similar arrangement, please contact me at the email address in my profile.

Meanwhile, you can use the standard Chaquopy builds, as described [here](https://chaquo.com/chaquopy/doc/current/android.html#gradle-plugin). These will work with any app.
