### ISSUE TITLE
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'x16'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1674]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>..<lambda>(<console>:1)
	at <python>.threading.run(threading.py:864)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:34)
	at <python>.six.reraise(six.py:693)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:25)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy3.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'x16'
```

Reporter
------------

This issue was reported by 3 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 9 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 
| 4.0.13-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 10 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 
| 4.2.3-2  | 3.8.6 (default, Dec 15 2020, 21:54:41)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Google sdk_gphone_x86_arm (generic_x86_arm) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
OK, that's crash reports working again: please close.

**Comment by cculianu** [comment]
Thanks man.

**Comment by ProfessorVenkman** [comment]
Good evening @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.0.13-0.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.0.11-0 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at <python>..<lambda>(<console>:1)
	at <python>.threading.run(threading.py:864)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:35)
	at <python>.six.reraise(six.py:693)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:26)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy3.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'x16'
```


~ _With robotic wishes_

**Comment by mhsmith** [comment]
Just me testing again, please ignore.

**Comment by ProfessorVenkman** [comment]
Good afternoon @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.3-2.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.0.13-0 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at <python>..<lambda>(<console>:1)
	at <python>.threading.run(threading.py:870)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:53)
	at <python>.six.reraise(six.py:693)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:44)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy4.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'x16'
```


~ _With robotic wishes_

**Comment by ProfessorVenkman** [comment]
Good morning @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.4-4.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.3-2 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at <python>..<lambda>(<console>:1)
	at <python>.threading.run(threading.py:870)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:53)
	at <python>.six.reraise(six.py:703)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:44)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
	at $Proxy3.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'x16'
```


~ _With robotic wishes_

**Comment by ProfessorVenkman** [comment]
Good evening @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.5-5.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.4-4 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at <python>..<lambda>(<console>:1)
	at <python>.threading.run(threading.py:870)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:53)
	at <python>.six.reraise(six.py:703)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:44)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
	at $Proxy3.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'x16'
```


~ _With robotic wishes_

**Comment by ProfessorVenkman** [comment]
Good evening @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.5-5.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.4-4 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at <python>..<lambda>(<console>:1)
	at <python>.threading.run(threading.py:870)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:53)
	at <python>.six.reraise(six.py:703)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:44)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
	at $Proxy3.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'x16'
```


~ _With robotic wishes_

**Comment by ProfessorVenkman** [comment]
Good evening @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.14-6.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.5-5 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at <python>..<lambda>(<console>:1)
	at <python>.threading.run(threading.py:870)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:53)
	at <python>.six.reraise(six.py:719)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:44)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:379)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:351)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy5.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'x16'
```


~ _With robotic wishes_
