### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder android.view.IWindowId.asBinder()' on a null object reference

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1702]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.view.WindowId.equals(WindowId.java:168)
	at android.transition.Transition.forceToEnd(Transition.java:1957)
	at android.transition.TransitionSet.forceToEnd(TransitionSet.java:504)
	at android.transition.TransitionManager.endTransitions(TransitionManager.java:452)
	at android.widget.PopupWindow$PopupDecorView.cancelTransitions(PopupWindow.java:2636)
	at android.widget.PopupWindow.dismiss(PopupWindow.java:1944)
	at androidx.appcompat.widget.ListPopupWindow.dismiss(ListPopupWindow.java:773)
	at androidx.appcompat.view.menu.StandardMenuPopup.dismiss(StandardMenuPopup.java:216)
	at androidx.appcompat.view.menu.MenuPopupHelper.dismiss(MenuPopupHelper.java:299)
	at androidx.appcompat.widget.ActionMenuPresenter.hideOverflowMenu(ActionMenuPresenter.java:366)
	at androidx.appcompat.widget.ActionMenuPresenter.dismissPopupMenus(ActionMenuPresenter.java:377)
	at androidx.appcompat.widget.ActionMenuView.dismissPopupMenus(ActionMenuView.java:724)
	at androidx.appcompat.widget.ActionMenuView.onDetachedFromWindow(ActionMenuView.java:545)
	at android.view.View.dispatchDetachedFromWindow(View.java:17611)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3729)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3736)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6835)
	at android.view.ViewRootImpl.die(ViewRootImpl.java:6805)
	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:493)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:424)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:206)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5196)
	at android.app.ActivityThread.-wrap6(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder android.view.IWindowId.asBinder()' on a null object reference
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 8.0.0 on HUAWEI LDN-L21 (HWLDN-Q) | unknown | de_DE | 

Additional Information
------------------------

> Netzwerk oder Software 

---

**Comment by mhsmith** [comment]
Can't find any explanation for this, but it looks like another OS bug outside of our control.
