### ISSUE TITLE
iOS XCode project built binary doesnt launch and exits with modulenotfound error

### ISSUE THREAD

**Issue by akshaynexus** [Electron-Cash/Electron-Cash#1705]
```2019-11-28 01:25:46.327292+0300 Electron-Cash[61395:12021965] PythonHome is: /Users/akshaycm/Library/Developer/CoreSimulator/Devices/36F7EEC1-659D-4FA9-8C36-B4CEE43459BA/data/Containers/Bundle/Application/8D10656D-E502-413B-BD59-9CD17571BD2F/Electron-Cash.app/Library/Python
2019-11-28 01:25:46.328841+0300 Electron-Cash[61395:12021965] PYTHONPATH is: PYTHONPATH=/Users/akshaycm/Library/Developer/CoreSimulator/Devices/36F7EEC1-659D-4FA9-8C36-B4CEE43459BA/data/Containers/Bundle/Application/8D10656D-E502-413B-BD59-9CD17571BD2F/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app:/Users/akshaycm/Library/Developer/CoreSimulator/Devices/36F7EEC1-659D-4FA9-8C36-B4CEE43459BA/data/Containers/Bundle/Application/8D10656D-E502-413B-BD59-9CD17571BD2F/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app_packages
2019-11-28 01:25:46.328939+0300 Electron-Cash[61395:12021965] Initializing Python runtime...
2019-11-28 01:25:46.621295+0300 Electron-Cash[61395:12021965] Installing Python NSLog handler...
2019-11-28 01:25:46.783264+0300 Electron-Cash[61395:12021965] Running '/Users/akshaycm/Library/Developer/CoreSimulator/Devices/36F7EEC1-659D-4FA9-8C36-B4CEE43459BA/data/Containers/Bundle/Application/8D10656D-E502-413B-BD59-9CD17571BD2F/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/__main__.py'...
2019-11-28 01:25:46.900314+0300 Electron-Cash[61395:12021965] /Users/akshaycm/Library/Developer/CoreSimulator/Devices/36F7EEC1-659D-4FA9-8C36-B4CEE43459BA/data/Containers/Bundle/Application/8D10656D-E502-413B-BD59-9CD17571BD2F/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app_packages/rubicon/objc/ctypes_patch.py:24: UserWarning: rubicon.objc.ctypes_patch has only been tested with Python 3.4 through 3.6. The current version is sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0). Most likely things will work properly, but you may experience crashes if Python's internals have changed significantly.
2019-11-28 01:25:46.900548+0300 Electron-Cash[61395:12021965]   .format(sys.version_info)
2019-11-28 01:25:47.010420+0300 Electron-Cash[61395:12021965] Traceback (most recent call last):
2019-11-28 01:25:47.010657+0300 Electron-Cash[61395:12021965]   File "/Users/akshaycm/Library/Developer/CoreSimulator/Devices/36F7EEC1-659D-4FA9-8C36-B4CEE43459BA/data/Containers/Bundle/Application/8D10656D-E502-413B-BD59-9CD17571BD2F/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/__main__.py", line 16, in <module>
2019-11-28 01:25:47.010908+0300 Electron-Cash[61395:12021965]     import electroncash_gui.ios_native.appdelegate
2019-11-28 01:25:47.011062+0300 Electron-Cash[61395:12021965]   File "/Users/akshaycm/Library/Developer/CoreSimulator/Devices/36F7EEC1-659D-4FA9-8C36-B4CEE43459BA/data/Containers/Bundle/Application/8D10656D-E502-413B-BD59-9CD17571BD2F/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/__init__.py", line 30, in <module>
2019-11-28 01:25:47.011560+0300 Electron-Cash[61395:12021965]     from .gui import ElectrumGui
2019-11-28 01:25:47.011685+0300 Electron-Cash[61395:12021965]   File "/Users/akshaycm/Library/Developer/CoreSimulator/Devices/36F7EEC1-659D-4FA9-8C36-B4CEE43459BA/data/Containers/Bundle/Application/8D10656D-E502-413B-BD59-9CD17571BD2F/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/gui.py", line 35, in <module>
2019-11-28 01:25:47.012542+0300 Electron-Cash[61395:12021965]     from . import utils
2019-11-28 01:25:47.012710+0300 Electron-Cash[61395:12021965]   File "/Users/akshaycm/Library/Developer/CoreSimulator/Devices/36F7EEC1-659D-4FA9-8C36-B4CEE43459BA/data/Containers/Bundle/Application/8D10656D-E502-413B-BD59-9CD17571BD2F/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/utils.py", line 28, in <module>
2019-11-28 01:25:47.013574+0300 Electron-Cash[61395:12021965]     import sys, os, json, qrcode, qrcode.image.svg, tempfile, random, queue, threading, time, stat
2019-11-28 01:25:47.013789+0300 Electron-Cash[61395:12021965]   File "/Users/akshaycm/Library/Developer/CoreSimulator/Devices/36F7EEC1-659D-4FA9-8C36-B4CEE43459BA/data/Containers/Bundle/Application/8D10656D-E502-413B-BD59-9CD17571BD2F/Electron-Cash.app/Library/Python/lib/python37.zip/queue.py", line 16, in <module>
2019-11-28 01:25:47.014117+0300 Electron-Cash[61395:12021965] ModuleNotFoundError: No module named '_queue'
2019-11-28 01:25:47.014194+0300 Electron-Cash[61395:12021965] Application quit abnormally!
2019-11-28 01:25:47.024019+0300 Electron-Cash[61395:12021965] Leaving...
```

**Comment by cculianu** [comment]
You're doing something atypical I think.  It says you're using Python3.7. The instructions specifically call for Python 3.6...
