### ISSUE TITLE
java.lang.IllegalStateException: Fragment OpenWalletDialog{671e612 (35a21f3b-a6cc-4374-bba1-0efefca9f209) org.electroncash.electroncash3.OpenWalletDialog} declared target fragment WalletRenameDialog{53e1874 (20c79ce9-7fcf-4e81-875e-10fbbae54b71)} that does not belong to this FragmentManager!

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1720]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:805)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
java.lang.IllegalStateException: Fragment OpenWalletDialog{671e612 (35a21f3b-a6cc-4374-bba1-0efefca9f209) org.electroncash.electroncash3.OpenWalletDialog} declared target fragment WalletRenameDialog{53e1874 (20c79ce9-7fcf-4e81-875e-10fbbae54b71)} that does not belong to this FragmentManager!
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 9 on samsung SM-G960F (starlte) | unknown | en_GB | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
@Andrew-128: to avoid confusion, it's better not to send crash reports to GitHub from unreleased development versions. You should be able to get the stack trace from the Android Studio Logcat window.
