### ISSUE TITLE
"File name too long" can cause crash on Android

### ISSUE THREAD

**Issue by mhsmith** [Electron-Cash/Electron-Cash#1760]
We got this crash report when someone pasted a big block of text in the wallet name box:

```
        at <python>.electroncash.storage._write(storage.py:197)
	at <python>.electroncash.storage.write(storage.py:181)
	at <python>.electroncash.util.do_profile(util.py:334)
	at <python>.electroncash.util.<lambda>(util.py:338)
	at <python>.electroncash.wallet.save_addresses(wallet.py:2375)
	at <python>.electroncash.wallet.import_address(wallet.py:2396)
	at <python>.electroncash.wallet.from_text(wallet.py:2350)
	at <python>.electroncash_gui.android.console.create(console.py:141)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at org.electroncash.electroncash3.NewWalletImportDialog.onCreateWallet(NewWallet.kt:193)
	at org.electroncash.electroncash3.NewWalletDialog2.doInBackground(NewWallet.kt:101)
	at org.electroncash.electroncash3.NewWalletDialog2.doInBackground(NewWallet.kt:84)
	at org.electroncash.electroncash3.LaunchedTaskDialog.doInBackground(Dialog.kt:244)
	at org.electroncash.electroncash3.TaskDialog$onStart$1.run(Dialog.kt:184)
	at java.lang.Thread.run(Thread.java:818)
com.chaquo.python.PyException: OSError: [Errno 36] File name too long: [redacted]
```

This probably also affects the new wallet rename function.

**Comment by mhsmith** [comment]
When renaming:

```
com.chaquo.python.PyException: OSError: [Errno 36] File name too long: '/data/data/org.electroncash.wallet/files/data/wallets/zz9' -> '/data/data/org.electroncash.wallet/files/data/wallets/zz9012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789'
        at <python>.electroncash_gui.android.console.rename_wallet(console.py:194)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
        at org.electroncash.electroncash3.WalletRenameDialog$onShowDialog$1.onClick(Main.kt:561)
        at android.view.View.performClick(View.java:6597)
```
