### ISSUE TITLE
electroncash.plugins.DeviceUnpairableError + frozen app after creating new seed and connecting

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1781]
Linux Mint 19
Electron 4.0.12 AppImage

- Just finished moving coins off of trezor with electron
- Update trezor to latest firmware (1.8.3)
- Use new dialog to create new seed on trezor
- When it tries to complete the process (I forget exactly what happens), it freezes and I have to force kill Electron.

![image](https://user-images.githubusercontent.com/34025062/72886125-97189180-3d4c-11ea-86ed-faa999695fe8.png)

From the console (not in verbose mode):
```
Traceback (most recent call last):
  File "/tmp/.mount_electrivqRNJ/usr/lib/python3.6/site-packages/electroncash_plugins/hw_wallet/qt.py", line 225, in run
    result = task.task()
  File "/tmp/.mount_electrivqRNJ/usr/lib/python3.6/site-packages/electroncash_plugins/trezor/trezor.py", line 185, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/tmp/.mount_electrivqRNJ/usr/lib/python3.6/site-packages/electroncash/plugins.py", line 793, in client_for_keystore
    client = self.force_pair_xpub(plugin, handler, info, xpub, derivation, devices)
  File "/tmp/.mount_electrivqRNJ/usr/lib/python3.6/site-packages/electroncash/plugins.py", line 838, in force_pair_xpub
    'receive will be unspendable.').format(plugin.device))
electroncash.plugins.DeviceUnpairableError: Electron Cash cannot pair with your Trezor.
```

**Comment by emergent-reasons** [comment]
This happened before it managed to create the wallet file, but the trezor has the wallet name and I assume new seed intact.

**Comment by emergent-reasons** [comment]
After restarting electron and connecting to existing HW wallet, everything seems fine. :man_shrugging:

**Comment by emergent-reasons** [comment]
I ran again with `-v` and got a different result. This time it did the same process all fine to the same point. After I input the pin and clicked OK, it immediately crashed without the frozen dialog and with this error that looks more actionable than the other:

```
Traceback (most recent call last):
  File "/tmp/.mount_electrxY6BHs/usr/lib/python3.6/site-packages/electroncash_plugins/hw_wallet/qt.py", line 121, in passphrase_dialog
    d = PasswordDialog(parent, None, msg, PW_PASSPHRASE)
TypeError: __init__() takes from 1 to 3 positional arguments but 5 were given
Aborted (core dumped)
```

**Comment by emergent-reasons** [comment]
From a quick look. The call in `plugins/hw_wallet/qt.py` looks like this:
```python
d = PasswordDialog(parent, None, msg, PW_PASSPHRASE)
```

Which indeed does not seem to match the init in `gui/qt/password_dialog.py`:
```python
class PasswordDialog(WindowModalDialog):

    def __init__(self, parent=None, msg=None):
```

Maybe it is supposed to be calling `PassphraseDialog`? That name makes more sense at least and the args seem to match: 
```python
class PassphraseDialog(WindowModalDialog):
    ''' Use this window to query the user to input a passphrase eg for
    things like the Bip38 export facility in the GUI. '''
    def __init__(self, wallet, parent=None, msg=None, title=None, permit_empty=False):
```
