### ISSUE TITLE
android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_menu_overflow_material.xml from drawable resource ID #0x7f080022. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1795]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.content.res.Resources.loadDrawable(Resources.java:2233)
	at android.content.res.Resources.getDrawable(Resources.java:743)
	at androidx.appcompat.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:130)
	at androidx.appcompat.widget.TintResources.getDrawable(TintResources.java:46)
	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:456)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
	at androidx.appcompat.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:59)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
	at androidx.appcompat.widget.ActionMenuPresenter$OverflowMenuButton.<init>(ActionMenuPresenter.java:634)
	at androidx.appcompat.widget.ActionMenuPresenter.initForMenu(ActionMenuPresenter.java:113)
	at androidx.appcompat.view.menu.MenuBuilder.addMenuPresenter(MenuBuilder.java:270)
	at androidx.appcompat.widget.ActionMenuView.getMenu(ActionMenuView.java:659)
	at androidx.appcompat.widget.Toolbar.ensureMenu(Toolbar.java:1155)
	at androidx.appcompat.widget.Toolbar.getMenu(Toolbar.java:1126)
	at androidx.appcompat.widget.ToolbarWidgetWrapper.getMenu(ToolbarWidgetWrapper.java:677)
	at androidx.appcompat.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:548)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:448)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5120)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_menu_overflow_material.xml from xml type drawable resource ID #0x7f080022
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2499)
	at android.content.res.Resources.loadDrawable(Resources.java:2227)
	... 28 more
Caused by: java.io.FileNotFoundException: Corrupt XML binary file
	at android.content.res.AssetManager.openXmlAssetNative(Native Method)
	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:504)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2481)
	... 29 more
android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_menu_overflow_material.xml from drawable resource ID #0x7f080022. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 4.4.4 on OPPO HOT D9 (A11) | unknown | en_US | 

Additional Information
------------------------

> I cant enter the app again nd i don't know the cause

---

**Comment by mhsmith** [comment]
Looks like an OS bug outside of our control. The linked Xamarin issue doesn't have a solution either.
