### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.chaquo.python.PyObject.toLong()' on a null object reference

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1807]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at org.electroncash.electroncash3.TransactionDialog.onShowDialog(Transactions.kt:121)
	at org.electroncash.electroncash3.AlertDialogFragment.onStart(Dialog.kt:79)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6615)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.chaquo.python.PyObject.toLong()' on a null object reference
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 8.1.0 on TCL 6062W (A70AXLTMO) | unknown | en_US | 

Additional Information
------------------------

> port 7683

---

**Comment by mhsmith** [comment]
Caused by viewing a transaction with an unknown timestamp. The transaction list can handle this because it uses the back end to format the timestamp, but the details dialog uses a different API.
