### ISSUE TITLE
java.lang.IndexOutOfBoundsException: setSpan (69 ... 69) ends beyond length 67

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1822]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1018)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:611)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:607)
	at android.text.Selection.setSelection(Selection.java:76)
	at android.text.Selection.setSelection(Selection.java:87)
	at android.widget.Editor.onDrop(Editor.java:2218)
	at android.widget.TextView.onDragEvent(TextView.java:9353)
	at android.view.View.dispatchDragEvent(View.java:18541)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5340)
	at android.view.ViewRootImpl.access$700(ViewRootImpl.java:108)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3461)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5431)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
java.lang.IndexOutOfBoundsException: setSpan (69 ... 69) ends beyond length 67
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 5.1.1 on LGE LGMS345 (c50) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Like #1092 and #1732, I can't reproduce this, and it doesn't seem to involve any of our code.
