### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.electroncash.wallet/org.electroncash.electroncash3.MainActivity}: java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: Exception: Daemon already running

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1833]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2330)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5261)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:734)
Caused by: java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: Exception: Daemon already running
	at android.app.LoadedApk.makeApplication(LoadedApk.java:576)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2235)
	... 10 more
Caused by: com.chaquo.python.PyException: Exception: Daemon already running
	at <python>.electroncash_gui.android.console.__init__(console.py:81)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at org.electroncash.electroncash3.DaemonModel.<init>(Daemon.kt:24)
	at org.electroncash.electroncash3.DaemonKt.initDaemon(Daemon.kt:19)
	at org.electroncash.electroncash3.App.onCreate(App.kt:63)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
	... 11 more
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.electroncash.wallet/org.electroncash.electroncash3.MainActivity}: java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: Exception: Daemon already running
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 5.0.2 on LENOVO Lenovo S60-a (sisleylr) | unknown | in_ID | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
No reports in last 6 months, and none from the current version.
