### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.electroncash.wallet/org.electroncash.electroncash3.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: androidx.recyclerview.widget.RecyclerView$SavedState

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1904]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3108)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3259)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1978)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:232)
	at android.app.ActivityThread.main(ActivityThread.java:7172)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: androidx.recyclerview.widget.RecyclerView$SavedState
	at android.os.Parcel.readParcelableCreator(Parcel.java:2855)
	at android.os.Parcel.readParcelable(Parcel.java:2781)
	at android.os.Parcel.readValue(Parcel.java:2684)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3134)
	at android.os.Parcel.readSparseArray(Parcel.java:2367)
	at android.os.Parcel.readValue(Parcel.java:2741)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
	at android.os.BaseBundle.unparcel(BaseBundle.java:232)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1010)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2195)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1189)
	at org.electroncash.electroncash3.MainActivity.onRestoreInstanceState(Main.kt:262)
	at org.electroncash.electroncash3.MainActivity.onCreate(Main.kt:104)
	at android.app.Activity.performCreate(Activity.java:7295)
	at android.app.Activity.performCreate(Activity.java:7286)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
	... 11 more
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.electroncash.wallet/org.electroncash.electroncash3.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: androidx.recyclerview.widget.RecyclerView$SavedState
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 9 on OPPO RMX1801 (RMX1801) | unknown | ms_MY | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Probably an OS bug outside of our control.
