### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mPrivateFlags' on a null object reference

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1905]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.view.ViewGroup.resetCancelNextUpFlag(ViewGroup.java:2815)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2718)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3040)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2720)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3040)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2720)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3040)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2720)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3040)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2720)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3040)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2720)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:467)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:847)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:425)
	at android.view.View.dispatchPointerEvent(View.java:12798)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5132)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4935)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4505)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4471)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4611)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4479)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4668)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4505)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4471)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4479)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7118)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7087)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7048)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7222)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:201)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6865)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mPrivateFlags' on a null object reference
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 9 on TCL 5024A (Faraday) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Looks like an OS bug outside of our control.
