### ISSUE TITLE
TypeError: get_passphrase() got an unexpected keyword argument 'available_on_device'

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1965]
with trezor firmware 1.9.2, the following happens when opening a trezor-based wallet:

passphrase entry dialog is not shown, instead a dialog box with text "get_passphrase() got an unexpected keyword argument 'available_on_device'" is popped up.

```
nick@x :-) ~$ ./Electron-Cash-4.1.0-x86_64.AppImage    
Traceback (most recent call last):
  File "/tmp/.mount_Electrwe568C/usr/lib/python3.6/site-packages/electroncash_plugins/hw_wallet/qt.py", line 225, in run
    result = task.task()
  File "/tmp/.mount_Electrwe568C/usr/lib/python3.6/site-packages/electroncash_plugins/trezor/trezor.py", line 190, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/tmp/.mount_Electrwe568C/usr/lib/python3.6/site-packages/electroncash/plugins.py", line 879, in client_for_keystore
    client = self.force_pair_xpub(plugin, handler, info, xpub, derivation, devices)
  File "/tmp/.mount_Electrwe568C/usr/lib/python3.6/site-packages/electroncash/plugins.py", line 909, in force_pair_xpub
    client_xpub = client.get_xpub(derivation, xtype)
  File "/tmp/.mount_Electrwe568C/usr/lib/python3.6/site-packages/electroncash_plugins/trezor/clientbase.py", line 142, in get_xpub
    node = trezorlib.btc.get_public_node(self.client, address_n).node
  File "/tmp/.mount_Electrwe568C/usr/lib/python3.6/site-packages/trezorlib/tools.py", line 202, in wrapped_f
    ret = f(*args, **kwargs)
  File "/tmp/.mount_Electrwe568C/usr/lib/python3.6/site-packages/trezorlib/btc.py", line 69, in get_public_node
    script_type=script_type,
  File "/tmp/.mount_Electrwe568C/usr/lib/python3.6/site-packages/trezorlib/tools.py", line 223, in wrapped_f
    return f(client, *args, **kwargs)
  File "/tmp/.mount_Electrwe568C/usr/lib/python3.6/site-packages/trezorlib/client.py", line 219, in call
    resp = self._callback_passphrase(resp)
  File "/tmp/.mount_Electrwe568C/usr/lib/python3.6/site-packages/trezorlib/client.py", line 184, in _callback_passphrase
    passphrase = self.ui.get_passphrase(available_on_device=available_on_device)
TypeError: get_passphrase() got an unexpected keyword argument 'available_on_device'
```

strangely I don't get this error when running from source tag 4.1.0

**Comment by EchterAgo** [comment]
This is fixed already by #1947 

The reason you don't see it from a source checkout is because you have an older Trezor library version in your Python environment.
