### ISSUE TITLE
terzor firmware 1.9.2: KeyError: b'\x89\xab\xf1\xb0\x99E$I\xb4\x90\x82\xe5\xee\x82\x11\xc0V\x02y\xb6\x81\xd0

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1966]
when trying to sign a tx from a trezor-based wallet with trezor firmware 1.9.2, I get the following error:

```
./electron-cash:96: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Electron-Cash not found at '/home/nick/Electron-Cash'
Use env var ELECTRON_CASH_HOME to change path
Traceback (most recent call last):
  File "/home/nick/bitcoin/electron-cash/gui/qt/util.py", line 967, in run
    result = task.task()
  File "/home/nick/bitcoin/electron-cash/lib/wallet.py", line 2233, in sign_transaction
    k.sign_transaction(tx, password, use_cache=use_cache)
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/trezor.py", line 87, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/trezor.py", line 351, in sign_transaction
    signatures, signed_tx = client.sign_tx(self.get_coin_name(), inputs, outputs, details=details, prev_txes=prev_tx)
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/clientbase.py", line 236, in sign_tx
    return trezorlib.btc.sign_tx(self.client, *args, **kwargs)
  File "/home/nick/bitcoin/electron-cash/venv_electron-cash/lib/python3.8/site-packages/trezorlib/tools.py", line 233, in wrapped_f
    return f(client, *args, **kwargs)
  File "/home/nick/bitcoin/electron-cash/venv_electron-cash/lib/python3.8/site-packages/trezorlib/btc.py", line 159, in sign_tx
    current_tx = txes[res.details.tx_hash]
KeyError: b'\x89\xab\xf1\xb0\x99E$I\xb4\x90\x82\xe5\xee\x82\x11\xc0V\x02y\xb6\x81\xd0\x81\xcfsp*\xadY@x$'
```

Opening the wallet (with passphrase) works fine, signing messages also works.

An older trezor (same seed, same wallet) with firmware 1.6.3 works fine.

**Comment by EchterAgo** [comment]
This is fixed already by #1900

**Comment by molecular** [comment]
great! Thank you!

**Comment by darkbluelight** [comment]
Hi, I'm urgently waiting for Electron-Cash to work again with my Trezor. Any estimation when the next release including #1900 will be made available?
