### ISSUE TITLE
java.io.FileNotFoundException: exampletx.txn (Read-only file system)

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1976]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:287)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:84)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:110)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:110)
	at org.electroncash.electroncash3.ColdSendPasswordDialog.onPassword(ColdSend.kt:301)
	at org.electroncash.electroncash3.ColdSendPasswordDialog.onPassword(ColdSend.kt:270)
	at org.electroncash.electroncash3.PasswordDialog.doInBackground(Dialog.kt:322)
	at org.electroncash.electroncash3.LaunchedTaskDialog.doInBackground(Dialog.kt:279)
	at org.electroncash.electroncash3.TaskDialog$onStart$1.run(Dialog.kt:219)
	at java.lang.Thread.run(Thread.java:764)
java.io.FileNotFoundException: exampletx.txn (Read-only file system)
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.1.0-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 8.0.0 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 
| 4.1.0-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 8.0.0 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 

Additional Information
------------------------

> mpatc adding coldsend

---

**Comment by mhsmith** [comment]
Development build.
