### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.chaquo.python.PyObject.asList()' on a null object reference

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1977]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at org.electroncash.electroncash3.ColdSendPasswordDialog.onPassword(ColdSend.kt:298)
	at org.electroncash.electroncash3.ColdSendPasswordDialog.onPassword(ColdSend.kt:270)
	at org.electroncash.electroncash3.PasswordDialog.doInBackground(Dialog.kt:322)
	at org.electroncash.electroncash3.LaunchedTaskDialog.doInBackground(Dialog.kt:279)
	at org.electroncash.electroncash3.TaskDialog$onStart$1.run(Dialog.kt:219)
	at java.lang.Thread.run(Thread.java:764)
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.chaquo.python.PyObject.asList()' on a null object reference
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.1.0-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 8.0.0 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 

Additional Information
------------------------

> mpatc problem with asList by

---

**Comment by mhsmith** [comment]
Development build.
