### ISSUE TITLE
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1979]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.os.Handler.<init>(Handler.java:203)
	at android.os.Handler.<init>(Handler.java:117)
	at android.content.ClipboardManager$2.<init>(ClipboardManager.java:62)
	at android.content.ClipboardManager.<init>(ClipboardManager.java:62)
	at android.app.SystemServiceRegistry$11.createService(SystemServiceRegistry.java:249)
	at android.app.SystemServiceRegistry$11.createService(SystemServiceRegistry.java:247)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:928)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:880)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:1651)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:708)
	at android.content.Context.getSystemService(Context.java:3157)
	at androidx.core.content.ContextCompat.getSystemService(ContextCompat.java:713)
	at org.electroncash.electroncash3.UtilKt.getSystemService(Util.kt:104)
	at org.electroncash.electroncash3.UtilKt.copyToClipboard(Util.kt:95)
	at org.electroncash.electroncash3.ColdSendPasswordDialog.onPassword(ColdSend.kt:289)
	at org.electroncash.electroncash3.ColdSendPasswordDialog.onPassword(ColdSend.kt:269)
	at org.electroncash.electroncash3.PasswordDialog.doInBackground(Dialog.kt:322)
	at org.electroncash.electroncash3.LaunchedTaskDialog.doInBackground(Dialog.kt:279)
	at org.electroncash.electroncash3.TaskDialog$onStart$1.run(Dialog.kt:219)
	at java.lang.Thread.run(Thread.java:764)
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.1.0-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 8.0.0 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 
| 4.1.0-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 8.0.0 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 

Additional Information
------------------------

> mpatc clipboard error

---

**Comment by mhsmith** [comment]
Development build.

**Comment by mhsmith** [comment]
@mpatc: You can see crash stack traces in Android Studio's Logcat window, so there's no point in sending them to the issue tracker as well: they just cause clutter.

**Comment by mpatc** [comment]
sorry misclick
