### ISSUE TITLE
java.lang.ClassCastException: org.electroncash.electroncash3.ColdSendDialog cannot be cast to org.electroncash.electroncash3.SendDialog

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1980]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at org.electroncash.electroncash3.ColdSendPasswordDialog$coldsendDialog$2.invoke(ColdSend.kt:270)
	at org.electroncash.electroncash3.ColdSendPasswordDialog$coldsendDialog$2.invoke(ColdSend.kt:269)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.electroncash.electroncash3.ColdSendPasswordDialog.getColdsendDialog(Unknown Source:7)
	at org.electroncash.electroncash3.ColdSendPasswordDialog.onFirstShowDialog(ColdSend.kt:282)
	at org.electroncash.electroncash3.AlertDialogFragment.onStart(Dialog.kt:97)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:73)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:63)
	at org.electroncash.electroncash3.ColdSendDialog.onOK(ColdSend.kt:214)
	at org.electroncash.electroncash3.ColdSendDialog$onShowDialog$5.onClick(ColdSend.kt:91)
	at android.view.View.performClick(View.java:6256)
	at android.view.View$PerformClick.run(View.java:24701)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
java.lang.ClassCastException: org.electroncash.electroncash3.ColdSendDialog cannot be cast to org.electroncash.electroncash3.SendDialog
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.1.0-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 8.0.0 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 
| 4.1.0-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 8.0.0 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Development build.
