### ISSUE TITLE
com.chaquo.python.PyException: AttributeError: 'str' object has no attribute 'txid'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1993]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.electroncash.network.broadcast_transaction2(network.py:1824)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at org.electroncash.electroncash3.ColdLoadDialog.onOK(ColdLoad.kt:79)
	at org.electroncash.electroncash3.ColdLoadDialog$onShowDialog$2.onClick(ColdLoad.kt:48)
	at android.view.View.performClick(View.java:7125)
	at android.view.View.performClickInternal(View.java:7102)
	at android.view.View.access$3500(View.java:801)
	at android.view.View$PerformClick.run(View.java:27336)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
com.chaquo.python.PyException: AttributeError: 'str' object has no attribute 'txid'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.1.0-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 10 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 

Additional Information
------------------------

> ssdf

---

**Comment by mhsmith** [comment]
Development build by @mpatc.
