### ISSUE TITLE
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: SyntaxError: invalid syntax (wallet.py, line 823)

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1998]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: com.chaquo.python.PyException: SyntaxError: invalid syntax (wallet.py, line 823)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.electroncash.<module>(__init__.py:3)
	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:678)
	at <python>.java.android.importer.exec_module(importer.py:346)
	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:665)
	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:994)
	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:941)
	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:994)
	at <python>.importlib.import_module(__init__.py:126)
	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:154)
	at com.chaquo.python.Python.getModule(Native Method)
	at org.electroncash.electroncash3.AppKt.libMod(App.kt:26)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Network.kt:27)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Unknown Source:0)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.electroncash.electroncash3.NetworkKt.getLibNetwork(Unknown Source:7)
	at org.electroncash.electroncash3.SettingsKt.setDefaultValues(Settings.kt:45)
	at org.electroncash.electroncash3.SettingsKt.initSettings(Settings.kt:23)
	at org.electroncash.electroncash3.App.onCreate(App.kt:63)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
	... 8 more
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: SyntaxError: invalid syntax (wallet.py, line 823)
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.1.0-0  | 3.6.5 (default, Sep 11 2019, 15:49:59)  [GCC 4.9] | Android 10 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Development build.
