### ISSUE TITLE
iOS: 'pip.internal' has no attribute 'download' error

### ISSUE THREAD

**Issue by PramodJoshi** [Electron-Cash/Electron-Cash#2098]
Hi, i'm trying to build iOS binary as per the instructions provided [here](https://github.com/Electron-Cash/Electron-Cash/tree/master/ios). I was able to install all the required packages but `./make_ios_project.sh` is throwing an attribute error. Complete error log below,

```
Building Briefcase-Based iOS Project...

running ios
 * Writing application template...
Template Python-iOS-template succesfully updated.
Project template: /Users/pro/.cookiecutters/Python-iOS-template
 * Determining best support package...
 * Installing support package...
Support package: https://pybee-briefcase-support.s3-us-west-2.amazonaws.com/Python-Apple-support/3.6/iOS/Python-3.6-iOS-support.b7.tar.gz
Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    'rubicon-objc'
  File "/Users/pro/Library/Python/3.6/lib/python/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/pro/Library/Python/3.6/lib/python/site-packages/briefcase/app.py", line 475, in run
    self.install_support_package()
  File "/Users/pro/Library/Python/3.6/lib/python/site-packages/briefcase/app.py", line 420, in install_support_package
    pip.download.unpack_url(
AttributeError: module 'pip._internal' has no attribute 'download'
An error occurred running setup.py
```

### System, tools and package versions:
Mac OS: High Sierra (10.13.6)
Xcode: 10.1
python3: 3.6.0
briefcase: 0.2.6
cookiecutter: 1.6.0
pbxproj: 2.5.1
pip: 20.3.1
pip-tools: 5.4.0
setuptools: 40.6.2

Any ideas?

**Comment by PramodJoshi** [comment]
Instructions doc doesn't mention this but it seems like you need **pip 18.0** to `./make_ios_project.sh`.
