### ISSUE TITLE
"KeyError: None" when running ./electron-cash --testnet -wp password

### ISSUE THREAD

**Issue by gasull** [Electron-Cash/Electron-Cash#2101]
```Python
Traceback (most recent call last):
  File "./electron-cash", line 530, in <module>
    main()
  File "./electron-cash", line 508, in main
    init_cmdline(config_options, server)
  File "./electron-cash", line 257, in init_cmdline
    cmd = known_commands[cmdname]
KeyError: None
```

**Comment by gasull** [comment]
This happens because [`set_default_subparser`](https://github.com/Electron-Cash/Electron-Cash/blob/764a37c822250eff2bdda09ea19dee4e2fc9a2b5/electroncash/commands.py#L942) never sets the default subparser to `'gui'`.

I find it hard to follow the logic in `set_default_subparser`.
