### ISSUE TITLE
com.chaquo.python.PyException: TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2133]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.ecdsa.ecdsa.__init__(ecdsa.py:89)
	at <python>.electroncash.bitcoin.__init__(bitcoin.py:641)
	at <python>.electroncash.address.from_WIF_privkey(address.py:311)
	at <python>.electroncash.keystore.import_privkey(keystore.py:187)
	at <python>.electroncash.wallet.import_private_key(wallet.py:2965)
	at <python>.electroncash.wallet.from_text(wallet.py:2918)
	at <python>.electroncash_gui.android.console.create(console.py:144)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.electroncash.electroncash3.NewWalletImportDialog.onCreateWallet(NewWallet.kt:210)
	at org.electroncash.electroncash3.NewWalletDialog2.doInBackground(NewWallet.kt:115)
	at org.electroncash.electroncash3.NewWalletDialog2.doInBackground(NewWallet.kt:98)
	at org.electroncash.electroncash3.LaunchedTaskDialog.doInBackground(Dialog.kt:297)
	at org.electroncash.electroncash3.TaskDialog$onStart$1.run(Dialog.kt:235)
	at java.lang.Thread.run(Thread.java:929)
com.chaquo.python.PyException: TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on HUAWEI STK-L22 (HWSTK-HF) | unknown | en_MY | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
See discussion in #1165. Since this has now been reported twice on Android and not on any other platform, there might be something different about the way the Android app validates its input.

**Comment by mhsmith** [comment]
`is_private_key` accepts the following types of keys which are not accepted by `from_WIF_privkey`.

Zero keys (which cause this crash):

```
>>> EncodeBase58Check(b"\x80" + b"\x00" * 32)
'5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kEsreAbuatmU'
>>> EncodeBase58Check(b"\x80" + b"\x00" * 32 + b"\x01")
'KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73Nd2Mcv1'
```

p2sh keys (which cause a different crash which has never been reported):

```
>>> EncodeBase58Check(b"\x85" + b"\x00" * 32)
'5TY1TqhFLax7w7Hoa6YtrejzoAuWTf5Tf1RKSvVED9tadmUMYjX'
```

I'll change the app to use `from_WIF_privkey` directly as a validation function, so there will be no risk of disagreement.
