### ISSUE TITLE
java.lang.IllegalStateException: FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2154]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1660)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:112)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:102)
	at org.electroncash.electroncash3.SendDialog.onPostExecute(Send.kt:295)
	at org.electroncash.electroncash3.SendDialog.onPostExecute(Send.kt:26)
	at org.electroncash.electroncash3.LaunchedTaskDialog.onPostExecute(Dialog.kt:300)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1$lambda$1.invoke(Dialog.kt:213)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1$lambda$1.invoke(Dialog.kt:201)
	at org.electroncash.electroncash3.TaskDialog.onFinished(Dialog.kt:249)
	at org.electroncash.electroncash3.TaskDialog.access$onFinished(Dialog.kt:201)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1.onChanged(LiveData.kt:52)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:442)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:394)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2637)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2619)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:257)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:551)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7157)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3037)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6819)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
java.lang.IllegalStateException: FragmentManager is already executing transactions
```

Reporter
------------

This issue was reported by 26 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on TECNO MOBILE LIMITED TECNO KC3 (TECNO-KC3) | unknown | en_US | 
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on TECNO MOBILE LIMITED TECNO KC3 (TECNO-KC3) | unknown | en_US | 
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on TECNO MOBILE LIMITED TECNO KC3 (TECNO-KC3) | unknown | en_US | 
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on TECNO MOBILE LIMITED TECNO KC3 (TECNO-KC3) | unknown | en_US | 
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on TECNO MOBILE LIMITED TECNO KC3 (TECNO-KC3) | unknown | en_US | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on samsung SM-A105M (a10) | unknown | pt_BR | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on samsung SM-A105M (a10) | unknown | pt_BR | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2003J15SC (merlinnfc) | unknown | es_ES | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on OUKITEL C21 (C21) | unknown | en_US | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on OUKITEL C21 (C21) | unknown | en_US | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on OUKITEL C21 (C21) | unknown | en_US | 

Additional Information
------------------------

> Não está enviando transações 

---

**Comment by mhsmith** [comment]
I tried to work around this by posting the code to the UI thread, but that caused the crash #2244. Both crashes are probably caused by a task completing during a rotation:

#2244 happens when onPostExecute runs after the old fragment has been destroyed.
#2154 happens when onPostExecute runs while the new fragment is being started.

The code that causes #2154 is simpler and fits better with the fragment lifecycle, so I've reverted to it until I come up with another solution.

**Comment by ProfessorVenkman** [comment]
Good morning @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.4-5.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.3-2 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1660)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:117)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:107)
	at org.electroncash.electroncash3.SendDialog.onPostExecute(Send.kt:421)
	at org.electroncash.electroncash3.SendDialog.onPostExecute(Send.kt:30)
	at org.electroncash.electroncash3.LaunchedTaskDialog.onPostExecute(Dialog.kt:306)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1$lambda$1.invoke(Dialog.kt:219)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1$lambda$1.invoke(Dialog.kt:207)
	at org.electroncash.electroncash3.TaskDialog.onFinished(Dialog.kt:255)
	at org.electroncash.electroncash3.TaskDialog.access$onFinished(Dialog.kt:207)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1.onChanged(LiveData.kt:52)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:442)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:394)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2637)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2619)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:257)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:551)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8124)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3546)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
java.lang.IllegalStateException: FragmentManager is already executing transactions
```


~ _With robotic wishes_

**Comment by ProfessorVenkman** [comment]
Good evening @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.5-5.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.4-5 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1660)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:117)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:107)
	at org.electroncash.electroncash3.SendDialog.onPostExecute(Send.kt:421)
	at org.electroncash.electroncash3.SendDialog.onPostExecute(Send.kt:30)
	at org.electroncash.electroncash3.LaunchedTaskDialog.onPostExecute(Dialog.kt:306)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1$lambda$1.invoke(Dialog.kt:219)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1$lambda$1.invoke(Dialog.kt:207)
	at org.electroncash.electroncash3.TaskDialog.onFinished(Dialog.kt:255)
	at org.electroncash.electroncash3.TaskDialog.access$onFinished(Dialog.kt:207)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1.onChanged(LiveData.kt:52)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:442)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:394)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2637)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2619)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:257)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:551)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8124)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3546)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:183)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:132)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
java.lang.IllegalStateException: FragmentManager is already executing transactions
```


~ _With robotic wishes_

**Comment by mhsmith** [comment]
Some of the new APIs for inter-fragment communication may be useful here: https://www.youtube.com/watch?v=OE-tDh3d1F4
