### ISSUE TITLE
com.chaquo.python.PyException: AttributeError: 'NoneType' object has no attribute 'tip'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2173]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.electroncash.network.get_server_height(network.py:421)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.electroncash.electroncash3.CaptionKt.getCaption(Caption.kt:59)
	at org.electroncash.electroncash3.CaptionKt.access$getCaption(Caption.kt:1)
	at org.electroncash.electroncash3.CaptionKt$caption$1$1.invoke(Caption.kt:23)
	at org.electroncash.electroncash3.CaptionKt$caption$1$1.invoke(Unknown Source:2)
	at org.electroncash.electroncash3.BackgroundLiveData$refreshNow$1.run(LiveData.kt:97)
	at java.lang.Thread.run(Thread.java:764)
com.chaquo.python.PyException: AttributeError: 'NoneType' object has no attribute 'tip'
```

Reporter
------------

This issue was reported by 6 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on samsung SM-A530F (jackpotlte) | unknown | nl_NL | 
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on HMD Global TA-1044 (ND1) | unknown | es_MX | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on samsung SM-A107M (a10s) | unknown | pt_BR | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on HMD Global TA-1044 (ND1) | unknown | es_MX | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on samsung SM-G970F (beyond0) | unknown | en_AU | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on samsung SM-A105M (a10) | unknown | pt_BR | 

Additional Information
------------------------

> She's not confirming the transactions is all getting pending 

---

**Comment by mhsmith** [comment]
get_server_height should have used interface_lock, so I'll add that. I'm not certain that the lock is used in all the other places that access self.interface, but let's wait and see whether this is enough to stop the crash reports.
