### ISSUE TITLE
old wallet won't open anymore

### ISSUE THREAD

**Issue by johnqube** [Electron-Cash/Electron-Cash#2182]
Hello

I claimed successfully my BCH years ago, and got them stored in electron-cash until now.
Unfortunately after 2 years of system updates the wallet won't open anymore :-(

I am looking for a way to recover my coins, or maybe I can claim them again?

Thank you

```
Traceback (most recent call last):
  File "/usr/local/bin/electron-cash", line 4, in <module>
    __import__('pkg_resources').run_script('Electron-Cash==3.0', 'electron-cash')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Electron-Cash==3.0' distribution was not found and is required by the application

```
Ubuntu 20.04.2 LTS
Python 2.7.18 (default, Aug  4 2020, 11:16:42)

**Comment by EchterAgo** [comment]
Hmmm, Python 2.7 on Ubuntu 20.04 with Electron-Cash 3.0. Those are some versions I wouldn't expect to see together :) Anyway, have you tried just using a recent .AppImage? Electron-Cash 3.0 is *old* and should not be used anymore due to fishing risks. Newer versions of the software should be able to open your old wallet, but make a backup of `~/.electron-cash` just in case.
