### ISSUE TITLE
Derivation scanner does not work with hardware wallets

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#2207]
Probably should be disabled or made to not crash.

**Comment by EchterAgo** [comment]
@jonas-lundqvist

```
---------------------------
Report contents
---------------------------
<h2>Traceback</h2>
<pre>
Traceback (most recent call last):
  File "C:\dev\Electron-Cash\electroncash_gui\qt\installwizard.py", line 687, in run
    k = keystore.from_seed(self.seed, '', derivation=p, seed_type=self.seed_type)
  File "C:\dev\Electron-Cash\electroncash\keystore.py", line 775, in from_seed
    raise InvalidSeed()
electroncash.keystore.InvalidSeed

</pre>

<h2>Additional information</h2>
<ul>
  <li>Electron Cash version: 4.2.4</li>
  <li>Python version: 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 07:55:33) [MSC v.1916 32 bit (Intel)]</li>
  <li>Operating system: Windows-10-10.0.21327-SP0</li>
  <li>Wallet type: standard</li>
  <li>Locale: en_SG</li>
</ul>

---------------------------
OK   
---------------------------
```

**Comment by cculianu** [comment]
Ugh yeah -- I can put in a commit later today to skip it for hw wallets.  Also I am curious what happens on multisig as well.. although theoretically with those it should work (if the keystore is set up correctly).

Likely it will crash there too -- so yeah this needs a fix ASAP. Will do it later today or later this week at the latest.

Thanks for the report man.
