### ISSUE TITLE
Building iOS app on HighSierra. Installing requirements fails.

### ISSUE THREAD

**Issue by Beakerboy** [Electron-Cash/Electron-Cash#2228]
I installed MacPorts and installed python 3.6 with Macports. I also installed all the dependencies. When trying to run the makefile, I get the following failure:
```
MacBook-Pro:ios kevin$ ./make_ios_project.sh 
You are using pip version 18.0, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 18.0, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 18.0, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 18.0, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Pulling 'electroncash' libs into project from ../electroncash ...
Removing electroncash/tests...

Building Briefcase-Based iOS Project...

running ios
 * Writing application template...
Template Python-iOS-template succesfully updated.
Project template: /Users/kevin/.cookiecutters/Python-iOS-template
 * Determining best support package...
 * Installing support package...
Support package: https://pybee-briefcase-support.s3-us-west-2.amazonaws.com/Python-Apple-support/3.6/iOS/Python-3.6-iOS-support.b7.tar.gz
 * Installing requirements...
Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    'rubicon-objc==0.2.10'
  File "/Users/kevin/Library/Python/3.6/lib/python/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/kevin/Library/Python/3.6/lib/python/site-packages/briefcase/app.py", line 476, in run
    self.install_app_requirements()
  File "/Users/kevin/Library/Python/3.6/lib/python/site-packages/briefcase/app.py", line 283, in install_app_requirements
    stderr=subprocess.STDOUT,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pip', 'install', '--upgrade', '--force-reinstall', '--target=/Users/kevin/development/git/Electron-Cash/ios/iOS/app_packages', 'certifi', 'chardet', 'dnspython', 'ecdsa>=0.9', 'idna', 'jsonrpclib-pelix', 'protobuf', 'pyaes>=0.1a1', 'PySocks>=1.6.6', 'qrcode', 'requests', 'six', 'stem==1.8.0', 'urllib3<1.24', 'python-dateutil==2.6.1', 'pathvalidate==2.3.1']' returned non-zero exit status 1.
An error occurred running setup.py
```

`which python3` points to `/opt/local/bin/python3`.

Any help would be appreciated. I'm wishing to compile this from source to ensure that my development setup works. Then my plan is to switch to the SLP version of Electron cash to try to add some of the SLP features to that version of the mobile wallet. As an aside, I was able to successfully compile the Electron Cash SLP, OSX version from source on my setup. However,  I was using homebrew and not Macports.

**Comment by cculianu** [comment]
`which pip` .. what does that point to?  `pip --version`?

You may need to do `sudo port select pip` or somesuch to make `pip` point to `pip3` of Python 3.6...

**Comment by Beakerboy** [comment]
Thank you!
```
MacBook-Pro:~ kevin$ which pip
/Library/Frameworks/Python.framework/Versions/3.6/bin/pip

MacBook-Pro:~ kevin$ sudo port install py36-pip
MacBook-Pro:~ kevin$ sudo port select --set pip pip36
MacBook-Pro:ios kevin$ ./make_ios_project.sh

Operation Complete. An Xcode project has been generated in "iOS/"
```

On to the next step.

**Comment by cculianu** [comment]
Ha, glad that works.  Good luck. It's... going to be a long road ahead of you to get SLP working in EC on iOS (mainly lots of UI work to be done). But I commend the effort and good luck!.

**Comment by Beakerboy** [comment]
If I can just get it so that SLP tokens are not accidentally burned, I’d call that a win.

**Comment by cculianu** [comment]
It doesn’t burn tokens now. That’s been fixed for over a year.

**Comment by Beakerboy** [comment]
Ah! There are always warning with SLP to not send them to non-SLP wallets...and the standard Electron Cash wallet is never listed in the “safe list”...at least in a way that I’ve remembered it.

**Comment by cculianu** [comment]
All of the electron cashes have for at least the last year refused to spend UTXOs containing tokens in them.  This includes the iOS version.
