### ISSUE TITLE
java.lang.IllegalStateException: etTransaction must not be null

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2230]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at org.electroncash.electroncash3.ColdLoadDialog.updateUI(ColdLoad.kt:45)
	at org.electroncash.electroncash3.ColdLoadDialog.access$updateUI(ColdLoad.kt:19)
	at org.electroncash.electroncash3.ColdLoadDialog$onShowDialog$1.invoke(ColdLoad.kt:30)
	at org.electroncash.electroncash3.ColdLoadDialog$onShowDialog$1.invoke(ColdLoad.kt:19)
	at org.electroncash.electroncash3.UtilKt$addAfterTextChangedListener$1.afterTextChanged(Util.kt:137)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:8270)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10541)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1043)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:560)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:34)
	at android.widget.TextView.paste(TextView.java:9817)
	at android.widget.TextView.onTextContextMenuItem(TextView.java:9465)
	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3548)
	at com.android.internal.policy.PhoneWindow$DecorView$ActionModeCallback2Wrapper.onActionItemClicked(PhoneWindow.java:3582)
	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:85)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
	at com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:111)
	at com.android.internal.widget.FloatingToolbar$FloatingToolbarMainPanel$1.onClick(FloatingToolbar.java:1057)
	at android.view.View.performClick(View.java:5210)
	at android.view.View$PerformClick.run(View.java:21294)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5527)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
java.lang.IllegalStateException: etTransaction must not be null
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 6.0 on LGE LGMS631 (g4stylusn) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
I can't see how this is possible. It can't be the full-screen input method situation that I speculated in #1701, because the stack trace shows that the paste is happening directly on our own TextView, whereas in a full-screen input method I think there would be a separate TextView running in the input method's process syncing its changes back and forth.

It's on an old version of Android and it's only been reported by one person, so it's not worth looking into just now.
