### ISSUE TITLE
com.chaquo.python.PyException: OSError: Cannot read wallet file '/data/data/org.electroncash.wallet/files/data/wallets/f.tmp.10248'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2232]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.electroncash.storage.load_data(storage.py:100)
	at <python>.electroncash.storage.__init__(storage.py:84)
	at <python>.electroncash_gui.android.console.load_wallet(console.py:116)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.electroncash.electroncash3.DaemonModel.loadWallet(Daemon.kt:74)
	at org.electroncash.electroncash3.WalletOpenDialog.onPassword(Main.kt:402)
	at org.electroncash.electroncash3.WalletOpenDialog.onPassword(Main.kt:398)
	at org.electroncash.electroncash3.PasswordDialog.doInBackground(Dialog.kt:342)
	at org.electroncash.electroncash3.LaunchedTaskDialog.doInBackground(Dialog.kt:297)
	at org.electroncash.electroncash3.TaskDialog$onStart$1.run(Dialog.kt:235)
	at java.lang.Thread.run(Thread.java:764)
com.chaquo.python.PyException: OSError: Cannot read wallet file '/data/data/org.electroncash.wallet/files/data/wallets/f.tmp.10248'
```

Reporter
------------

This issue was reported by 4 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 8.1.0 on ZTE Z559DL (Z559DL) | unknown | en_US | 
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 8.1.0 on ZTE Z559DL (Z559DL) | unknown | en_US | 
| 4.2.3-2  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 8.1.0 on ZTE Z559DL (Z559DL) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on samsung SM-A015T1 (a01q) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Probably caused by an incomplete temporary file being left behind by a previous process. Because the process ID is different, it won't be hidden from the wallet list.
