### ISSUE TITLE
com.chaquo.python.PyException: FileExistsError: /data/data/org.electroncash.wallet/files/data/wallets/s

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2238]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.electroncash_gui.android.console.create(console.py:142)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.electroncash.electroncash3.NewWalletSeedDialog.onCreateWallet(NewWallet.kt:230)
	at org.electroncash.electroncash3.NewWalletDialog2.doInBackground(NewWallet.kt:172)
	at org.electroncash.electroncash3.NewWalletDialog2.doInBackground(NewWallet.kt:155)
	at org.electroncash.electroncash3.LaunchedTaskDialog.doInBackground(Dialog.kt:301)
	at org.electroncash.electroncash3.TaskDialog$onStart$1.run(Dialog.kt:235)
	at java.lang.Thread.run(Thread.java:919)
com.chaquo.python.PyException: FileExistsError: /data/data/org.electroncash.wallet/files/data/wallets/s
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.4-3  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on Xiaomi Redmi Note 8 Pro (begonia) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Apparently from the same device as #2241 and #2243.
