### ISSUE TITLE
com.chaquo.python.PyException: KeyError: '/data/data/org.electroncash.wallet/files/data/wallets/a'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2243]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.electroncash_gui.android.console.select_wallet(console.py:195)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.electroncash.electroncash3.NewWalletDialog2.onPostExecute(NewWallet.kt:270)
	at org.electroncash.electroncash3.NewWalletDialog2.onPostExecute(NewWallet.kt:189)
	at org.electroncash.electroncash3.LaunchedTaskDialog.onPostExecute(Dialog.kt:304)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1$lambda$1.invoke(Dialog.kt:213)
	at org.electroncash.electroncash3.TaskDialog$onCreateDialog$$inlined$observe$1$lambda$1.invoke(Dialog.kt:201)
	at org.electroncash.electroncash3.TaskDialog$onFinished$1.invoke(Dialog.kt:252)
	at org.electroncash.electroncash3.TaskDialog$onFinished$1.invoke(Dialog.kt:201)
	at org.electroncash.electroncash3.AppKt$postToUiThread$1.run(App.kt:64)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
com.chaquo.python.PyException: KeyError: '/data/data/org.electroncash.wallet/files/data/wallets/a'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.4-3  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on Xiaomi Redmi Note 8 Pro (begonia) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
We never made a release with this version number, so this must be someone running their own build.
