### ISSUE TITLE
com.chaquo.python.PyException: OverflowError: int too big to convert

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2288]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_toLong(chaquopy_java.pyx:278)
	at com.chaquo.python.PyObject.toLong(Native Method)
	at org.electroncash.electroncash3.ExchangeKt.fiatToSatoshis(Exchange.kt:36)
	at org.electroncash.electroncash3.AmountBox$1$2.invoke(AmountBox.kt:40)
	at org.electroncash.electroncash3.AmountBox$1$2.invoke(AmountBox.kt:10)
	at org.electroncash.electroncash3.AmountBox$1.invoke(AmountBox.kt:49)
	at org.electroncash.electroncash3.AmountBox$1.invoke(AmountBox.kt:10)
	at org.electroncash.electroncash3.UtilKt$addAfterTextChangedListener$1.afterTextChanged(Util.kt:137)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:10837)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13791)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
	at android.widget.TextView.paste(TextView.java:13009)
	at android.widget.TextView.onTextContextMenuItem(TextView.java:12457)
	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4280)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2801)
	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:98)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:151)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:123)
	at com.android.internal.view.-$$Lambda$FloatingActionMode$LU5MpPuKYDtwlFAuYhXYfzgLNLE.onMenuItemClick(Unknown Source:2)
	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:459)
	at android.view.View.performClick(View.java:7288)
	at android.view.View.performClickInternal(View.java:7258)
	at android.view.View.access$4000(View.java:808)
	at android.view.View$PerformClick.run(View.java:28019)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7615)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
com.chaquo.python.PyException: OverflowError: int too big to convert
```

Reporter
------------

This issue was reported by 4 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 

Additional Information
------------------------

> (_ssl.c:1124)bitcoincash:12gQAuhSEzAHb6Sx8xbu8GVmaQVcVdXwG4?amount=0.00147025&message=%28_ssl.c%3A1124%29

---

> android10 on lge. stelob

---

> node-ovhook

---

**Comment by mhsmith** [comment]
Unlike #2288, this could have been caused by an extremely small exchange rate. However I don't see any such rates in a live system. And since it was reported by the same person at the same time as #2288, it was probably caused by the same unknown thing.

It can also be caused by entering a very large fiat number, so I'll fix that.
