### ISSUE TITLE
java.lang.ClassCastException: TypeError: Cannot convert int object to boolean

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2298]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.java.chaquopy.p2j(conversion.pxi:256)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_toBoolean(chaquopy_java.pyx:210)
	at com.chaquo.python.PyObject.toBoolean(Native Method)
	at org.electroncash.electroncash3.SendKt.checkExpired(Send.kt:393)
	at org.electroncash.electroncash3.SendKt.access$checkExpired(Send.kt:1)
	at org.electroncash.electroncash3.GetPaymentRequestDialog.doInBackground(Send.kt:316)
	at org.electroncash.electroncash3.GetPaymentRequestDialog.doInBackground(Send.kt:303)
	at org.electroncash.electroncash3.TaskDialog$onStart$1.run(Dialog.kt:235)
	at java.lang.Thread.run(Thread.java:929)
java.lang.ClassCastException: TypeError: Cannot convert int object to boolean
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on HUAWEI COL-L29 (HWCOL) | unknown | en_GB | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on HUAWEI COL-L29 (HWCOL) | unknown | en_GB | 

Additional Information
------------------------

> Testing my bip 70 implementation. 

---

**Comment by mhsmith** [comment]
Apparently caused by a payment request with no expiration date, which would cause has_expired to return zero instead of False.
