### ISSUE TITLE
java.lang.RuntimeException: Unable to resume activity {org.electroncash.wallet/org.electroncash.electroncash3.MainActivity}: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2310]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4010)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4042)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1986)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:215)
	at android.app.ActivityThread.main(ActivityThread.java:6939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by: java.lang.IllegalArgumentException
	at android.os.Parcel.createException(Parcel.java:1954)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.isTopOfTask(IActivityManager.java:7872)
	at android.app.Activity.isTopOfTask(Activity.java:6423)
	at android.app.Activity.onResume(Activity.java:1352)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:456)
	at org.electroncash.electroncash3.MainActivity.onResume(Main.kt:286)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1434)
	at android.app.Activity.performResume(Activity.java:7304)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4002)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.isTopOfTask(ActivityManagerService.java:15191)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2341)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3567)
	at android.os.Binder.execTransact(Binder.java:746)
java.lang.RuntimeException: Unable to resume activity {org.electroncash.wallet/org.electroncash.electroncash3.MainActivity}: java.lang.IllegalArgumentException
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on motorola moto e6 (XT2005DL) (surfna) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Looks like an OS bug outside of our control. I can find several other examples of it on Google, but no solutions.
