### ISSUE TITLE
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: ImportError: dlopen failed: library "/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/armeabi-v7a.zip/unicodedata.so" not found

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2357]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5943)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:232)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: com.chaquo.python.PyException: ImportError: dlopen failed: library "/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/armeabi-v7a.zip/unicodedata.so" not found
	at <python>.load_dynamic(stdlib/imp.py:343)
	at <python>.load_module_impl(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:503)
	at <python>.load_module(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:353)
	at <python>.java.chaquopy.import_override(import.pxi:18)
	at <python>.reraise(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/_vendor/six.py:686)
	at <python>.java.chaquopy.import_override(import.pxi:59)
	at <python>.<module>(/android_asset/chaquopy/app.zip/electroncash/keystore.py:27)
	at <python>.load_module_impl(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:435)
	at <python>.load_module(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:353)
	at <python>.java.chaquopy.import_override(import.pxi:18)
	at <python>.reraise(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/_vendor/six.py:686)
	at <python>.java.chaquopy.import_override(import.pxi:59)
	at <python>.<module>(/android_asset/chaquopy/app.zip/electroncash/wallet.py:48)
	at <python>.load_module_impl(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:435)
	at <python>.load_module(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:353)
	at <python>.java.chaquopy.import_override(import.pxi:18)
	at <python>.reraise(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/_vendor/six.py:686)
	at <python>.java.chaquopy.import_override(import.pxi:59)
	at <python>.<module>(/android_asset/chaquopy/app.zip/electroncash/__init__.py:3)
	at <python>.load_module_impl(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:435)
	at <python>.load_module(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:353)
	at <python>._load_backward_compatible(<frozen importlib._bootstrap>:626)
	at <python>._load_unlocked(<frozen importlib._bootstrap>:656)
	at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
	at <python>._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>._gcd_import(<frozen importlib._bootstrap>:994)
	at <python>._call_with_frames_removed(<frozen importlib._bootstrap>:219)
	at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:941)
	at <python>._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>._gcd_import(<frozen importlib._bootstrap>:994)
	at <python>.import_module(stdlib/importlib/__init__.py:126)
	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:153)
	at com.chaquo.python.Python.getModule(Native Method)
	at org.electroncash.electroncash3.DaemonKt.libMod(Daemon.kt:15)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Network.kt:29)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Network.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.electroncash.electroncash3.NetworkKt.getLibNetwork(Network.kt)
	at org.electroncash.electroncash3.SettingsKt.initSettings(Settings.kt:27)
	at org.electroncash.electroncash3.App.onCreate(App.kt:43)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5940)
	... 8 more
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: ImportError: dlopen failed: library "/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/armeabi-v7a.zip/unicodedata.so" not found
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.1.1 on OPPO CPH1725 (CPH1725) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
This was fixed in Electron Cash 4.0.11-0 by moving to a newer version of Chaquopy which doesn't use the "cache" directory.
