### ISSUE TITLE
Python error at launch on Fedora35

### ISSUE THREAD

**Issue by JustALinuxUser** [Electron-Cash/Electron-Cash#2368]
Hello,
Electron-cash was working fine on Fedora34.
I've upgraded to FC35, now I have this error at launch:

$ electron-cash 
Traceback (most recent call last):
  File "/usr/bin/electron-cash", line 574, in <module>
    main()
  File "/usr/bin/electron-cash", line 562, in main
    result = run_gui(config, config_options)
  File "/usr/bin/electron-cash", line 356, in run_gui
    daemon_thread.init_gui()
  File "/usr/lib/python3.10/site-packages/electroncash/daemon.py", line 365, in init_gui
    self.gui = gui.ElectrumGui(config, self, plugins)
  File "/usr/lib/python3.10/site-packages/electroncash_gui/qt/__init__.py", line 153, in __init__
    self._start_auto_update_timer(first_run = True)
  File "/usr/lib/python3.10/site-packages/electroncash_gui/qt/__init__.py", line 763, in _start_auto_update_timer
    self.update_checker_timer.start(interval)
TypeError: arguments did not match any overloaded call:
  start(self, int): argument 1 has unexpected type 'float'
  start(self): too many arguments

Packages installed:
electron-cash-4.2.5-1.fc35.noarch (tried to re-install, no change)
python3.10-3.10.0-1.fc35.src.rpm (x86_64)
FC35 fully updated

**Comment by cculianu** [comment]
Yes, this is due to Fedora 35 using Python 3.10. On Python 3.10 PyQt has gotten a more restrictive API.  We have fixed this in `master` but unfortunately the released version of Electron Cash still has the problems.

I'm going to keep this open until we release 4.2.6 which should work ok on Fedora.
