### ISSUE TITLE
iOS No Hardware wallet found

### ISSUE THREAD

**Issue by sonic456** [Electron-Cash/Electron-Cash#2369]
Electron-Cash: Version: 4.2.5
iOS: 10.13.6
![Screen Shot 2021-11-28 at 16 32 21](https://user-images.githubusercontent.com/13707283/143777161-e9ced8ca-5b0b-4b3b-9c46-7bfc69e77a26.png)

No Hardware wallet found. Please see attached.

**Comment by EchterAgo** [comment]
You'll have to provide some more information. What hardware wallet are you using? Does it work with the manufacturers own software?

**Comment by sonic456** [comment]
Using Satochip hardware wallet and I don't think they have their own software

**Comment by EchterAgo** [comment]
@Toporin any idea?

I don't have macOS or Satochip to test, but IIRC it should show up as a smart card. Maybe try this utility:

https://twocanoes.com/products/mac/smart-card-utility/

See if that detects the smart card. Do you use a USB smart card reader? If so, it might be worth it to see if the device shows up with a macOS `lsusb` equivalent program.

**Comment by cculianu** [comment]
I'm on macos Big Sur, using the .dmg release of 4.2.5 downloaded from this github.  I was able to pair with my satochip, but it did spit out errors.  I could not sign a txn. 

Pairing ok:

<img width="873" alt="Screen Shot 2021-12-01 at 8 29 24 AM" src="https://user-images.githubusercontent.com/266627/144252980-01ca8d73-bd63-475e-b3d6-e1be67d00564.png">

However txn signing shows this error:

<img width="427" alt="Screen Shot 2021-12-01 at 8 36 17 AM" src="https://user-images.githubusercontent.com/266627/144253798-d3be5464-fe09-49af-89d3-4314dffb6af7.png">

With this in the log:

```
f9ae1450b6fdad9ac89d387a5cb67
DEBUG [CardConnector] card_verify_PIN | In card_verify_PIN
DEBUG [CardConnector] update | > B0 42 00 00 04 * * * *
DEBUG [CardConnector] update | < [] 90 00
| 82.868| |20| [SatochipClient] [get_xpub(): bip32_path =  m/44'/145'/0'
DEBUG [CardConnector] card_bip32_get_extendedkey | In card_bip32_get_extendedkey
DEBUG [CardConnector] card_transmit | In card_transmit
DEBUG [CardConnector] update | > B0 6D 03 40 0C 80 00 00 2C 80 00 00 91 80 00 00 00
DEBUG [CardConnector] update | < 4B AF 81 B3 33 E1 BA A0 82 0B 5F D9 D2 C7 7F 8E FF 4F C0 12 6B 96 D0 0A 05 18 EC 9F 75 94 A9 A6 00 20 57 D8 8F 21 E7 B3 C2 0A 0D 2D 73 28 F4 6A 8E C1 34 17 CA 2D 0A 43 FC A0 67 02 03 BC 8C 1F CA 85 00 46 30 44 02 20 40 A2 40 99 A9 E3 F9 F6 5C 47 C6 0D B7 34 14 39 61 AC 27 3B 30 3A 42 89 CA EC 29 65 87 A0 0F 70 02 20 25 BE DA 2B D0 9B 9A AC 72 83 D4 62 F6 72 90 7E 65 93 B5 8D C2 0F 57 AA C5 9B 89 91 1C C2 D5 80 00 47 30 45 02 21 00 BE 67 AA 63 71 DE 9E A8 FC AF CD 35 C2 FA 4A 1A D1 49 6D E0 41 9D A6 19 CF BA 79 0D 23 F3 6A F9 02 20 31 E1 17 0A CE E5 E2 45 EE D5 04 EF BC 01 39 DC 4D 41 04 E6 1C 13 D5 A7 00 17 84 1C 46 3D F8 D9 90 00
DEBUG [CardConnector] card_bip32_get_extendedkey | In card_bip32_get_extendedkey
DEBUG [CardConnector] card_transmit | In card_transmit
DEBUG [CardConnector] update | > B0 6D 02 40 08 80 00 00 2C 80 00 00 91
DEBUG [CardConnector] update | < B1 64 E9 36 9F 75 B4 B3 72 0F 67 D4 FD EC 50 B8 FA 82 FF 34 5E BC 90 DD C6 59 AE 12 D5 C1 55 72 00 20 2A EF 4E 25 7E 2C 66 77 EF 38 37 12 40 FD 31 7A 84 2B EA 20 19 7E 59 42 3D 5D 49 B9 BE 94 4F 41 00 47 30 45 02 20 16 B4 BB 9A 58 B2 1E 90 CF 18 05 8F 9F E6 AC FB DD 69 FE CF D0 50 63 95 A9 61 FB 0B 61 B1 1D 91 02 21 00 95 5C DB 65 58 D9 07 D2 BA 74 68 05 E9 10 68 62 9A 86 67 05 DB B8 4D 53 8A 47 0F AE F7 B5 2A E5 00 46 30 44 02 20 5B D4 FC 78 C4 9D 38 D6 81 44 07 41 3A 19 0C F3 F2 26 3E 76 CA 70 31 7E 83 72 36 C5 F1 FB 86 C6 02 20 37 0C 2B A7 8B 48 59 DB 52 E4 87 E0 23 E9 F6 A4 B8 53 00 21 9C 03 0F 64 07 A9 F0 98 6C 9C 48 9D 90 00
| 83.735| |20| [SatochipClient] SatochipClient: get_xpub(): xpub= xpub6Ct8rarFVxZ9Bmd7VS15U1tL6DAMhVT5RiXUejNgsRA4T1kzKJmbtUAEbhWL3gxed5sxQ3e2jXSdy5HWUrJJi6mkn1FS9FgbS5h3N9M4tRp
| 84.013| |20| [TaskThread] exiting
Traceback (most recent call last):
  File "/Users/calin/src/ec/electron-cash/electroncash_gui/qt/util.py", line 972, in run
    result = task.task()
  File "/Users/calin/src/ec/electron-cash/electroncash/wallet.py", line 2327, in sign_transaction
    k.sign_transaction(tx, password, use_cache=use_cache)
  File "/Users/calin/src/ec/electron-cash/electroncash_plugins/satochip/satochip.py", line 362, in sign_transaction
    client = self.get_client()
  File "/Users/calin/src/ec/electron-cash/electroncash_plugins/satochip/satochip.py", line 284, in get_client
    rv = self.plugin.get_client(self)
  File "/Users/calin/src/ec/electron-cash/electroncash_plugins/satochip/satochip.py", line 680, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/Users/calin/src/ec/electron-cash/electroncash/plugins.py", line 868, in client_for_keystore
    client = self.force_pair_xpub(plugin, handler, info, xpub, derivation, devices)
  File "/Users/calin/src/ec/electron-cash/electroncash/plugins.py", line 908, in force_pair_xpub
    raise DeviceUnpairableError(
electroncash.plugins.DeviceUnpairableError: Electron Cash cannot pair with your Satochip.
```

Not sure if my card reader is broken, if my card is oxidized, no idea.  I have a dollar-store card reader that cost like $5.  It *did* work in the past but it was finicky.

Yeah I think @Toporin  would be best to troubleshoot this.

**Comment by Toporin** [comment]
@sonic456 could you provide the logs generated using the -v flag (when run in command line)? These logs would be helpful to understand the issue. As far as I can tell, the card reader is not detected, what kind of card reader do you use? 

@cculianu it seems to be a different issue since the card is correctly detected and command/response are correctly exchanged with the card. I will try to reproduce it but in the meantime that would be great if you could check if this problem also arises with older releases and with windows/linux versions. The satochip version 0.8 is quite old: we aim for backward compatibility but new releases are not always thoroughly tested with the oldest firmware versions.

**Comment by Toporin** [comment]
Hi @cculianu,

I tried to reproduce your issue using the official Electron-cash v4.2.5 appimage for Linux and a new satochip wallet with the v0.8 firmware. I was able to make transactions and sign messages without problem (on the testnet).

If you are sure you opened the correct wallet file for the card, I have to dig deeper to try to reproduce the error. 

Maybe it is specific to the macos package? Could you try with the Linux appImage?
Could you try to sign a message instead of a transaction?
Could you recreate a new wallet file (File => New/Restore...) and try again?

**Comment by sonic456** [comment]
Hi Toporin,

What would be the command for me to execute in Terminal so I can record the
logs?

**Comment by Toporin** [comment]
@sonic456 this worked for me:

- Download the electron-cash *.dmg executable and install it (click on it)
- Open terminal and type `cd /Applications/Electron-Cash.app/`
- type again `cd Contents/MacOS`
- type `ls` to show content of folder, there should be a "Electron-Cash" file
- run the file with `./Electron-Cash -v --testnet`

The logs should be displayed on the terminal.
