### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mPrivateFlags' on a null object reference

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2372]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.view.ViewGroup.resetCancelNextUpFlag(ViewGroup.java:2779)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2678)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:449)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:815)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:411)
	at android.view.View.dispatchPointerEvent(View.java:12052)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4967)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4777)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4309)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4362)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4328)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4455)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4336)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4512)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4309)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4362)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4328)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4336)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4309)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6887)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6861)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6818)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6998)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mPrivateFlags' on a null object reference
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 8.1.0 on Alco RCT6513W87DK5e (RCT6513W87DK5e) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Looks like an OS bug outside of our control.
