### ISSUE TITLE
signtransaction --privkey  Documentation (and Possibly Behavior) Gaps and Issues

### ISSUE THREAD

**Issue by The00Dustin** [Electron-Cash/Electron-Cash#2375]
I wanted to figure out how to sign a transaction using the command line in a scenario where I have the private key, but the address is only available in a watching wallet.  Unfortunately, some time has passed since I tried this, so I don't remember which documentation I was referring to, but at the very least, there is a problem with the help output.  Beyond that, there may be an entire feature not working.  In order to test, I took a single address with a minimal amount of BCH and added it to a new watch-only wallet.  Then I used the GUI to generate a transaction from that address in the watch-only wallet using the following steps:

1. Fill out `Send` tab
2. Click `Preview` button
3. Click `Save` button to create a file called `unsigned.txn`

Next, based on help output, I ran `cat unsigned.txn | Electron-Cash signtransaction --privkey ? - > signed.txn` which returned `zsh: no matches found: ?`

Some searching lead me to believe that ? should actually be a : even though `Electron-Cash help signtransaction` output includes `--privkey PRIVKEY     Private key. Set to '?' to get a prompt.`

Based on that, I ran `cat unsigned.txn | Electron-Cash signtransaction --privkey : - > signed.txn` which prompted for the private key, but after I put in the private key, the command returned the error `Wallet "default_wallet" is not loaded. Use "electron-cash daemon load_wallet"`.

I don't really understand why specifying a wallet would be necessary, but I went ahead and selected the watch-only wallet because it is configured with no password, so simpler to deal with.  The command at this point was `cat unsigned.txn | Electron-Cash signtransaction --wallet watchtest --privkey : - > signed.txn` and no errors were returned.

Having seemingly successfully executed the command, I visually examined the contents of the `unsigned.txn` and `signed.txn` files and noticed that the hex section of the files appeared identical.  Running `cat signed.txn | Electron-Cash deserialize - > signed.json` and visually inspecting that file confirms the signatures remain null.  Running `cat unsigned.txn | Electron-Cash deserialize - > unsigned.json` and `diff unsigned.json signed.json` confirms that absolutely nothing changed when the `signtransaction` command was run.

FWIW, the behavior discussed in the two preceding paragraphs is also repeatable if I use a normal (HD) wallet file that is password protected (at which point I also have to use `--walletpassword`) and does not include the address from the watch-only wallet.

In case the problem could be that I didn't get the private key right, I also tried running the same command but inputting data other than a private key (to be specific, I tried the redeem script in case that was actually the way to go).  This returned the following error, which I believe confirms I had put in a good private key in prior tests:

```
Traceback (most recent call last):
  File "electron-cash", line 574, in <module>
  File "electron-cash", line 566, in main
  File "electron-cash", line 421, in run_cmdline
  File "jsonrpclib/jsonrpc.py", line 821, in __call__
  File "jsonrpclib/jsonrpc.py", line 696, in _request
  File "jsonrpclib/jsonrpc.py", line 1453, in check_for_errors
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "electroncash/bitcoin.py", line 446, in deserialize_privkey | ValueError: Not a valid private key: \'<truncated non-private-key input>\'\n')
[85982] Failed to execute script electron-cash
```

I know I can import the private key and make a transaction, and I know I can sweep the private key as well, so to be clear, the issue here isn't that I can't access my BCH.  I don't know whether or not the unsigned output from the `signtransaction` command with no error is an expected behavior, and I don't know what the `--privkey` switch on the `signtransaction` option could be for if not this.  That having been said, I am creating this issue to report the potential problems that follow.

Documentation (help output):

- `Set to '?' to get a prompt.` is inaccurate.  It may also extraneous (if a : could also be used on the password switches, where nothing similar is mentioned in the help output).
- There is no explanation in help regarding what the `--privkey` switch for `signtransaction` does.

Behavior:

- Should it be necessary to load or choose a specific wallet when the private key is being supplied in the CLI?  (In my testing, wallets were loaded in the GUI, so I didn't have to use `electron-cash daemon load_wallet` in order to have a wallet loaded, but I had to specify one of the GUI loaded wallets).
- Should `signtransaction` be able to complete without an error when the output hasn't been signed?

_All testing above was done on a Mac running Big Sur (11.6.1 & 11.6.2) using Electron Cash version 4.2.6._

**Comment by The00Dustin** [comment]
After starting to think I was crazy because I couldn't reproduce this, I think I figured out what it takes...  If the daemon is running, it insists on looking for a wallet regardless of whether or not a private key is provided, but I'm unsure what is leading to the unsigned output, as in one test, I was able to assign a wallet and still get an unsigned transaction, but adding the privkey from the wallet (literally copy/paste to CLI) got the transaction signed.  Regardless, if the daemon is not running, there won't be a prompt for a wallet when the private key is provided, presumably `init_cmdline` is only reached when the daemon isn't already running.  I also realized that the `?` option probably works outside of macOS, even as the `:` option is an additional valid option to have a prompt that doesn't echo, so the documentation concern my be moot.  OTOH, neither seems to work after `signtransaction` (which is where `--privkey` has to be used to function), at least not on macOS.  Further, I noticed that the JSON ouput will still have `"complete": false,` when the transaction isn't signed, so this behavior could be intentional, i.e. wrt multisig.  Given these intricacies, I'm not certain if the behavior of relying on the wallet only while the daemon is running would be considered buggy or if it's more like a design quirk...  Testing on other platforms might be necessary to determine whether there is a bug wrt `?` and `:` not being parsed from the CLI after `signtransaction`.

**Comment by The00Dustin** [comment]
Finally figured out what's happening with the `:` and `?`.  The `?` is treated specially by zsh on macos unless it is escaped or quoted, so that's why it never worked, and the `:` apparently works unless it is used after `-` after a pipe.
