### ISSUE TITLE
java.lang.IllegalStateException: Drag shadow dimensions must be positive

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2425]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.view.View.startDragAndDrop(View.java:24293)
	at android.widget.Editor.startDragAndDrop(Editor.java:1203)
	at android.widget.Editor.performLongClick(Editor.java:1229)
	at android.widget.TextView.performLongClick(TextView.java:11761)
	at android.view.View.performLongClick(View.java:6712)
	at android.view.View$CheckForLongPress.run(View.java:26130)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
java.lang.IllegalStateException: Drag shadow dimensions must be positive
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on HUAWEI HRY-LX1 (HWHRY-H) | unknown | ru_RU | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on HUAWEI HRY-LX1 (HWHRY-H) | unknown | ru_RU | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Looks like an OS bug outside of our control.
