### ISSUE TITLE
Add support for trezor 0.13.1 and higher

### ISSUE THREAD

**Issue by hegjon** [Electron-Cash/Electron-Cash#2465]
https://github.com/Electron-Cash/Electron-Cash/blob/81ad15c9f03bd40a5f903b86d4aa0fa1e1b43392/electroncash_plugins/trezor/trezor.py#L115

**Comment by hegjon** [comment]
It would be great if the requirements could be updated in sync, it will make it easier to get an overview of the supported version https://github.com/Electron-Cash/Electron-Cash/blob/81ad15c9f03bd40a5f903b86d4aa0fa1e1b43392/contrib/requirements/requirements-hw.txt#L2

**Comment by imaginaryusername** [comment]
I don't have a trezor to test, but are the one line changes expected to "just work". Can you put up a PR to test that?

**Comment by PiRK** [comment]
I have a commit in an open pull request in the Electrum ABC repo that should do the trick, but i haven't landed it because low impact (Trezor 0.12 still works) and lack of testers. It is mostly a backport of an Electrum commit. 

https://github.com/Bitcoin-ABC/ElectrumABC/pull/183/commits/6cb6b1e0e2d0648ef8e1313cc8218374f86cb6f1

It might require some additional tweaking for Electron Cash,because of minor Electrum/Electron Cash code divergence (i backported some Electrum stuff related to hardware wallets in ABC recently).

**Comment by hegjon** [comment]
I'm getting this error after chaning the one line: `TypeError: unhashable type: 'ButtonRequest'` not sure if it is related.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/electroncash_gui/qt/util.py", line 973, in run
    result = task.task()
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2351, in sign_transaction
    k.sign_transaction(tx, password, use_cache=use_cache)
  File "/usr/lib/python3.10/site-packages/electroncash_plugins/trezor/trezor.py", line 91, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/usr/lib/python3.10/site-packages/electroncash_plugins/trezor/trezor.py", line 355, in sign_transaction
    signatures, signed_tx = client.sign_tx(self.get_coin_name(), inputs, outputs, details=details, prev_txes=prev_tx)
  File "/usr/lib/python3.10/site-packages/electroncash_plugins/trezor/clientbase.py", line 245, in sign_tx
    return trezorlib.btc.sign_tx(self.client, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/trezorlib/tools.py", line 288, in wrapped_f
    return f(client, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/trezorlib/btc.py", line 391, in sign_tx
    res = client.call(messages.TxAck(tx=msg))
  File "/usr/lib/python3.10/site-packages/trezorlib/tools.py", line 288, in wrapped_f
    return f(client, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/trezorlib/client.py", line 254, in call
    resp = self._callback_button(resp)
  File "/usr/lib/python3.10/site-packages/trezorlib/client.py", line 241, in _callback_button
    self.ui.button_request(msg)
  File "/usr/lib/python3.10/site-packages/electroncash_plugins/trezor/clientbase.py", line 258, in button_request
    message = self.msg or MESSAGES.get(code) or MESSAGES['default']
```

**Comment by danger89** [comment]
> I don't have a trezor to test, but are the one line changes expected to "just work". Can you put up a PR to test that?

I could test.

**Comment by tl121** [comment]
I have a tested fix for this problem.  It allows Trezor 0.13.0 and higher to work with the Electron Cash 4.3.1 source code release.  This is needed for the new Trezor Safe 3 which I just got last week.  Support of the new library now has real functionality!

 In addition to tweaking the max version (so the 0.13.8 version needed by the Trezor Safe 3 is allowed) there was an incompatible interface change at 0.13.0 which required changing two lines in clientbase.py,  affecting the button_request routine.

See https://github.com/spesmilo/electrum/commit/9a975a5200e97d3dbba253ab0a8b3a88e485820e 

If this change as made and maximum_library = (0, 14) is set in trezor.py then all three versions of Trezor will sign messages and transactions.  It will be possible to test for compatibility with older Trezors.  However, unless the installed trezor library is 0.13.8 the Safe 3 will be rejected as "unsupported".  The above worked from the GUI running under Ubuntu 22.04, python 3.10.12, trezor 0.13.8.

Sorry for the lack of pull requests.  I am new to github and not sure how to do this properly. I have all three models of trezor and will be happy to test any software provided to me.

**Comment by imaginaryusername** [comment]
If folks can help test https://github.com/Electron-Cash/Electron-Cash/pull/2757 and comment on it that'll be awesome.

**Comment by cculianu** [comment]
I just went ahead and merged #2757, and I updated the requirements. Hopefully running-from-source users don't panic and upgrade their trezorlib..

**Comment by hegjon** [comment]
Would be nice to keep the minimal `0.13.x` instead of `0.13.8`

**Comment by tl121** [comment]
I think you made the right move, because it is quick for people to react to a specific error message syingwhat to do,while being told their new device is unsupported wastes a lot of time and gives a bad rep to Electron Cash  People who don't use Trezor will be unaffected in any event.

**Comment by cculianu** [comment]
So what should the minimum be?
