### ISSUE TITLE
Directory for chipnet data is not created by default with CLI create and daemon start

### ISSUE THREAD

**Issue by damascene** [Electron-Cash/Electron-Cash#2492]
Wallet complains about non existing directory when I try to create a new wallet for chipnet:
```bash
$ ./electron-cash create --chipnet
Traceback (most recent call last):
  File "./electron-cash", line 581, in <module>
    main()
  File "./electron-cash", line 565, in main
    run_non_rpc(config)
  File "./electron-cash", line 130, in run_non_rpc
    storage = WalletStorage(simple_config.get_wallet_path())
  File "/home/user/dev/electron-cash-wallet/src/Electron-Cash/electroncash/simple_config.py", line 230, in get_wallet_path
    util.assert_datadir_available(self.path)
  File "/home/user/dev/electron-cash-wallet/src/Electron-Cash/electroncash/util.py", line 382, in assert_datadir_available
    raise FileNotFoundError(
FileNotFoundError: Electron Cash datadir does not exist. Was it deleted while running?
Should be at /home/user/.electron-cash/chipnet
```

Also when I try to start the daemon:
```
$ ./electron-cash --dir ~/dev/wallet_test/ --chipnet daemon start
Unable to open/create lockfile at /home/user/dev/wallet_test/chipnet/daemon after 5 attempts. Please check your filesystem setup. Last error was: FileNotFoundError(2, 'No such file or directory')
```

However this doesn't seem to happen with any other network like `testnet4` or `scalenet`

Creating the required directory manually solves the issue.

**Comment by cculianu** [comment]
Hmm ok. I'll look into it. Likely something is missing and it will be a quick fix.

**Comment by cculianu** [comment]
Ok, fixed.  Missed a `make_dir()` call in the right place.  Sorry about that. Thanks for catching and reporting!
