### ISSUE TITLE
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://blockchair.com/... cmp=id.dana/.home.HomeTabActivity } from ProcessRecord{ac9f423 8486:org.electroncash.wallet/u0a747} (pid=8486, uid=10747) not exported from uid 10560

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2561]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.os.Parcel.createException(Parcel.java:2072)
	at android.os.Parcel.readException(Parcel.java:2040)
	at android.os.Parcel.readException(Parcel.java:1988)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4251)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1712)
	at android.app.Activity.startActivityForResult(Activity.java:5207)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
	at android.app.Activity.startActivityForResult(Activity.java:5165)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
	at android.app.Activity.startActivity(Activity.java:5536)
	at android.app.Activity.startActivity(Activity.java:5504)
	at org.electroncash.electroncash3.WebKt.openBrowser(Web.kt:27)
	at org.electroncash.electroncash3.WebKt.exploreAddress(Web.kt:14)
	at org.electroncash.electroncash3.ContactDialog$onShowDialog$3.onClick(Contacts.kt:86)
	at android.view.View.performClick(View.java:7156)
	at android.view.View.performClickInternal(View.java:7129)
	at android.view.View.access$3500(View.java:803)
	at android.view.View$PerformClick.run(View.java:27549)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:7684)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1121)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:895)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:676)
	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1896)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:607)
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://blockchair.com/... cmp=id.dana/.home.HomeTabActivity } from ProcessRecord{ac9f423 8486:org.electroncash.wallet/u0a747} (pid=8486, uid=10747) not exported from uid 10560
```

Reporter
------------

This issue was reported by 5 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on INFINIX MOBILITY LIMITED Infinix X692 (Infinix-X692) | unknown | in_ID | [ℹ](https://crashhub.electroncash.org//crash/2116) | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on INFINIX MOBILITY LIMITED Infinix X692 (Infinix-X692) | unknown | in_ID | [ℹ](https://crashhub.electroncash.org//crash/2117) | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on INFINIX MOBILITY LIMITED Infinix X692 (Infinix-X692) | unknown | in_ID | [ℹ](https://crashhub.electroncash.org//crash/2118) | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on INFINIX MOBILITY LIMITED Infinix X692 (Infinix-X692) | unknown | in_ID | [ℹ](https://crashhub.electroncash.org//crash/2119) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:31:08)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 10 on TECNO MOBILE LIMITED TECNO BC1 (TECNO-BC1) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2762) | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by ndreisg** [comment]
https://github.com/termux/termux-app/issues/3283
