### ISSUE TITLE
com.chaquo.python.PyException: NameError: name 'get_coin_name' is not defined

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2574]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.electroncash_plugins.fusion.android.spendable_coin_filter(android.py:51)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:379)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:351)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.electroncash.electroncash3.SendDialog$TxArgs.invoke(Send.kt:272)
	at org.electroncash.electroncash3.SendDialog$Model$tx$1$1.invoke(Send.kt:37)
	at org.electroncash.electroncash3.SendDialog$Model$tx$1$1.invoke(Send.kt:33)
	at org.electroncash.electroncash3.BackgroundLiveData$refreshNow$1.run(LiveData.kt:97)
	at java.lang.Thread.run(Thread.java:1012)
com.chaquo.python.PyException: NameError: name 'get_coin_name' is not defined
```

Reporter
------------

This issue was reported by 47 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-G991B (o1s) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2174) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2175) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2176) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2178) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2179) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2180) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2195) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2196) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2197) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2198) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2199) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2200) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2201) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2202) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2203) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2204) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2205) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 10 on samsung SM-G965U1 (star2qlteue) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2209) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 10 on samsung SM-G965U1 (star2qlteue) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2223) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2224) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on samsung SM-T500 (gta4lwifi) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2238) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 5a (barbet) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2268) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 10 on Alldocube iPlay_40 (T1020S) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2318) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 10 on Alldocube iPlay_40 (T1020S) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2319) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g32 (devon) | unknown | es_AR | [ℹ](https://crashhub.electroncash.org//crash/2352) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2407) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 11 on OnePlus ONEPLUS A3000 (OnePlus3T) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2414) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 11 on OnePlus ONEPLUS A3000 (OnePlus3T) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2415) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on samsung SM-N975U (d2q) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2429) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 7 (panther) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2691) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 4 (flame) | unknown | en_AU | [ℹ](https://crashhub.electroncash.org//crash/2761) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2102J20SG (vayu) | unknown | es_US | [ℹ](https://crashhub.electroncash.org//crash/2967) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/3273) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/3274) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/3275) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/3276) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g22 (hawaiip) | unknown | es_AR | [ℹ](https://crashhub.electroncash.org//crash/3508) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g22 (hawaiip) | unknown | es_AR | [ℹ](https://crashhub.electroncash.org//crash/3509) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g22 (hawaiip) | unknown | es_AR | [ℹ](https://crashhub.electroncash.org//crash/3510) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 10 on samsung SM-G960F (starlte) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/3759) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 10 on samsung SM-G960F (starlte) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/3777) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on Google Pixel 6a (bluejay) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/3983) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on Google Pixel 6a (bluejay) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/3984) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on Google Pixel 7a (lynx) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/4296) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on Google Pixel 6a (bluejay) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/4548) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on Google Pixel 6a (bluejay) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/4549) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on samsung SM-G973U1 (beyond1q) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/4915) | 

Additional Information
------------------------

> Tried to spend all coins and use only fused coins was enabled.

---

> Al querer enviar el saldo y tildar en la palomita de máximo salta el error

---

> I clicked on the QR code on BCHBull to fund a contract but it failed with this message. 

---

> From send screen - as soon as I type the first digit of the amount to send, then application crashes with this error message.

---

> Every time I type a non-zero value in the send amount field, the app crashes with the above error. I can type 0 and decimal point, but as soon as I type a 1 or any numeral between 1-9 the crash occurs. This has only started happening today. Up until now, Electron Cash has worked flawlessly. I have been using Cash Fusion in the background.

---

> entered an address, then crash, i think

---

> pasted an address in the send field and app crashed

---

> Crashed when trying to send with spend only fused coins enabled

---

> can't send

---

> uh oh

---

**Comment by ProfessorVenkman** [comment]
Good afternoon @fyookball,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.4.1-3.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.14-6 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at <python>.electroncash_plugins.fusion.android.spendable_coin_filter(android.py:51)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.electroncash.electroncash3.SendDialog$TxArgs.invoke(Send.kt:530)
	at org.electroncash.electroncash3.SendDialog$Model$tx$1$1.invoke(Send.kt:45)
	at org.electroncash.electroncash3.SendDialog$Model$tx$1$1.invoke(Send.kt:45)
	at org.electroncash.electroncash3.BackgroundLiveData.refreshNow$lambda$0(LiveData.kt:97)
	at org.electroncash.electroncash3.BackgroundLiveData.$r8$lambda$ztnHGqyNVLiGXJ2PfdcY2tHl-hQ(Unknown Source:0)
	at org.electroncash.electroncash3.BackgroundLiveData$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
com.chaquo.python.PyException: NameError: name 'get_coin_name' is not defined
```


~ _With robotic wishes_
