### ISSUE TITLE
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service org.electroncash.wallet/org.electroncash.electroncash3.CaptionService

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2578]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4787)
	at android.os.Parcel.readParcelable(Parcel.java:4755)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3018)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6201)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1967)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1933)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
	at org.electroncash.electroncash3.CaptionKt$initCaption$2.onChanged(Caption.kt:42)
	at org.electroncash.electroncash3.CaptionKt$initCaption$2.onChanged(Unknown Source:2)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at org.electroncash.electroncash3.BackgroundLiveData.refreshDone(LiveData.kt:105)
	at org.electroncash.electroncash3.BackgroundLiveData.access$refreshDone(LiveData.kt:47)
	at org.electroncash.electroncash3.BackgroundLiveData$refreshNow$1$1.invoke(LiveData.kt:99)
	at org.electroncash.electroncash3.BackgroundLiveData$refreshNow$1$1.invoke(LiveData.kt:47)
	at org.electroncash.electroncash3.AppKt$runOnUiThread$1.run(App.kt:63)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8775)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service org.electroncash.wallet/org.electroncash.electroncash3.CaptionService
```

Reporter
------------

This issue was reported by 79 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-A146U (a14xm) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2220) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-A146U (a14xm) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2235) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-A146U (a14xm) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2239) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2286) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2287) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2288) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2289) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2290) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-M326B (a32x) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2328) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on samsung SM-G525F (xcover5) | unknown | fr_FR | [ℹ](https://crashhub.electroncash.org//crash/2337) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6 (oriole) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2374) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6 (oriole) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2375) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6 (oriole) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2376) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6 (oriole) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2418) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6 (oriole) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2419) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2435) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2436) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2443) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2445) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2447) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2448) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2449) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2451) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2452) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2453) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2454) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2455) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2456) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2457) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2468) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2469) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2476) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2485) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2488) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2489) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2490) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2491) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2492) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2498) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2499) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2500) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2501) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2502) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2504) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2505) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2510) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2515) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2516) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2517) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2518) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2519) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2520) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2523) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2528) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2529) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2531) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2532) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2534) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2535) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2536) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2554) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2555) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2556) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2561) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2562) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2563) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Google Pixel 6a (bluejay) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2564) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:31:08)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-A137F (a13ve) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/2724) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-A037W (a03su) | unknown | en_CA | [ℹ](https://crashhub.electroncash.org//crash/2768) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-A037W (a03su) | unknown | en_CA | [ℹ](https://crashhub.electroncash.org//crash/2930) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-A037W (a03su) | unknown | en_CA | [ℹ](https://crashhub.electroncash.org//crash/2931) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on samsung SM-S918B (dm3q) | unknown | de_DE | [ℹ](https://crashhub.electroncash.org//crash/3899) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on JOYAR 100044018P (100044018P) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/4105) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on BLU B1550VL (B1550VL) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/4240) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on samsung SM-S918B (dm3q) | unknown | de_DE | [ℹ](https://crashhub.electroncash.org//crash/4343) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 14 on samsung SM-S918B (dm3q) | unknown | de_DE | [ℹ](https://crashhub.electroncash.org//crash/4344) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on JOYAR 100044018P (100044018P) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/4411) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:31:08)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on BLU Studio Mini 2023 (ST1020T) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/4980) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on samsung SM-G970F (beyond0) | unknown | pt_BR | [ℹ](https://crashhub.electroncash.org//crash/5059) | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by ProfessorVenkman** [comment]
Good afternoon @fyookball,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.4.1-3.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.14-6 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6471)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2002)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1967)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:847)
	at com.chaquo.python.utils.ConsoleActivity$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
	at org.electroncash.electroncash3.CaptionKt$initCaption$2.invoke(Caption.kt:42)
	at org.electroncash.electroncash3.CaptionKt$initCaption$2.invoke(Caption.kt:36)
	at org.electroncash.electroncash3.CaptionKt$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at org.electroncash.electroncash3.BackgroundLiveData.refreshDone(LiveData.kt:105)
	at org.electroncash.electroncash3.BackgroundLiveData.access$refreshDone(LiveData.kt:46)
	at org.electroncash.electroncash3.BackgroundLiveData$refreshNow$1$1.invoke(LiveData.kt:99)
	at org.electroncash.electroncash3.BackgroundLiveData$refreshNow$1$1.invoke(LiveData.kt:99)
	at org.electroncash.electroncash3.AppKt.runOnUiThread$lambda$0(App.kt:63)
	at org.electroncash.electroncash3.AppKt.$r8$lambda$E2b2ig9Jfi1YpwYA1YrIGVoLaIM(Unknown Source:0)
	at org.electroncash.electroncash3.AppKt$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service org.electroncash.wallet/org.electroncash.electroncash3.CaptionService
```


~ _With robotic wishes_
