### ISSUE TITLE
Fails to build on Python 3.12

### ISSUE THREAD

**Issue by hegjon** [Electron-Cash/Electron-Cash#2661]
Build log from Fedora Linux 39 (unreleased) that will ship with Python 3.12:

```
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -sP'
Traceback (most recent call last):
  File "/builddir/build/BUILD/Electron-Cash-4.3.1/setup.py", line 10, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
error: Bad exit status from /var/tmp/rpm-tmp.lwVBNV (%build)
    Bad exit status from /var/tmp/rpm-tmp.lwVBNV (%build)
RPM build errors:
Child return code was: 1
EXCEPTION: [Error('Command failed: \n # /usr/bin/systemd-nspawn -q -M bde03a8e62b340dda4453be3c8c0dfa6 -D /var/lib/mock/f39-build-44244130-5272039/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.fzx6kcrc:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007" --setenv=PS1=<mock-chroot> \\s-\\v\\$  --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c /usr/bin/rpmbuild -bb --noclean --target noarch --nodeps /builddir/build/SPECS/electron-cash.spec\n', 1)]
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/util.py", line 597, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)

```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/2378/103522378/build.log

**Comment by EchterAgo** [comment]
This is because the imp module was removed in 3.12:

https://docs.python.org/3/library/imp.html

We should replace it with code like this:

https://github.com/epfl-scitas/spack/blob/af6a3556c4c861148b8e1adc2637685932f4b08a/lib/spack/llnl/util/lang.py#L595-L622

Since we only support Python >= 3.7 we can just use this:

```
import importlib.util
spec = importlib.util.spec_from_file_location(module_name, module_path)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
```

**Comment by EchterAgo** [comment]
https://github.com/Electron-Cash/Electron-Cash/pull/2662
