### ISSUE TITLE
Make a release that works with Python 3.12 

### ISSUE THREAD

**Issue by hegjon** [Electron-Cash/Electron-Cash#2704]
`master` contains several fixes for Python 3.12, it would be great to have a new release that contains these fixes.

Python 3.12 was released today https://www.python.org/downloads/release/python-3120/

**Comment by hegjon** [comment]
Just upgraded to Fedora 39, here is the output from the console:

```
$ electron-cash
Traceback (most recent call last):
  File "/usr/bin/electron-cash", line 581, in <module>
    main()
  File "/usr/bin/electron-cash", line 569, in main
    result = run_gui(config, config_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/electron-cash", line 353, in run_gui
    plugins = init_plugins(config, config.get("gui", "qt"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/electron-cash", line 346, in init_plugins
    return Plugins(config, gui_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/electroncash/util.py", line 357, in <lambda>
    return lambda *args, **kw_args: do_profile(args, kw_args)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/electroncash/util.py", line 353, in do_profile
    o = func(*args, **kw_args)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/electroncash/plugins.py", line 86, in __init__
    self.load_internal_plugins()
  File "/usr/lib/python3.12/site-packages/electroncash/plugins.py", line 137, in load_internal_plugins
    m = loader.find_module(name).load_module(name)
        ^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'
```
