### ISSUE TITLE
com.chaquo.python.PyException: FileExistsError: /data/data/org.electroncash.wallet/files/data/wallets

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2800]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.electroncash_gui.android.console.create(console.py:154)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:379)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:351)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.electroncash.electroncash3.NewWalletImportDialog.onCreateWallet(NewWallet.kt:369)
	at org.electroncash.electroncash3.NewWalletDialog2.doInBackground(NewWallet.kt:207)
	at org.electroncash.electroncash3.NewWalletDialog2.doInBackground(NewWallet.kt:183)
	at org.electroncash.electroncash3.LaunchedTaskDialog.doInBackground(Dialog.kt:303)
	at org.electroncash.electroncash3.TaskDialog$onStart$1.run(Dialog.kt:241)
	at java.lang.Thread.run(Thread.java:1012)
com.chaquo.python.PyException: FileExistsError: /data/data/org.electroncash.wallet/files/data/wallets
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on TECNO TECNO LH6n (TECNO-LH6n) | unknown | ru_RU | [ℹ](https://crashhub.electroncash.org//crash/3481) | 
| 4.2.14-6  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 11 on Xiaomi M2101K6G (sweet) | unknown | en_GB | [ℹ](https://crashhub.electroncash.org//crash/3550) | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by ProfessorVenkman** [comment]
Good morning @fyookball,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.4.1-3.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.14-6 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at <python>.electroncash_gui.android.console.create(console.py:154)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.electroncash.electroncash3.NewWalletSeedDialog.onCreateWallet(NewWallet.kt:374)
	at org.electroncash.electroncash3.NewWalletDialog2.doInBackground(NewWallet.kt:264)
	at org.electroncash.electroncash3.NewWalletDialog2.doInBackground(NewWallet.kt:222)
	at org.electroncash.electroncash3.LaunchedTaskDialog.doInBackground(Dialog.kt:296)
	at org.electroncash.electroncash3.TaskDialog.onStart$lambda$2(Dialog.kt:234)
	at org.electroncash.electroncash3.TaskDialog.$r8$lambda$uUsM55mGPeK7v4ioNBBGgOC48ZM(Unknown Source:0)
	at org.electroncash.electroncash3.TaskDialog$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
com.chaquo.python.PyException: FileExistsError: /data/data/org.electroncash.wallet/files/data
```


~ _With robotic wishes_
