### ISSUE TITLE
Error loading partially signed tx with a p2sh/p2pk input

### ISSUE THREAD

**Issue by defunct-operator** [Electron-Cash/Electron-Cash#2958]
Ran into this when trying to use my [tx editor](https://github.com/defunct-operator/bch-tx-editor) to manually create an unsigned withdrawal transaction for Emerald DAO. It seems like `parse_scriptSig` thinks the p2sh input is p2pk [because the scriptSig is just a single pushdata](https://github.com/Electron-Cash/Electron-Cash/blob/master/electroncash/transaction.py#L100-L109), and that means `x_pubkey` below is just `"(pubkey)"`, hence the parse error.

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/electroncash_gui/qt/main_window.py", line 3697, in do_process_from_text
    self.show_transaction(tx)
  File "/usr/lib/python3.12/site-packages/electroncash_gui/qt/main_window.py", line 1138, in show_transaction
    d = show_transaction(tx, self, tx_desc, broadcast_callback=broadcast_callback)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/electroncash_gui/qt/transaction_dialog.py", line 60, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved, broadcast_callback=broadcast_callback)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/electroncash_gui/qt/transaction_dialog.py", line 205, in __init__
    self.update()
  File "/usr/lib/python3.12/site-packages/electroncash_gui/qt/transaction_dialog.py", line 477, in update
    (self.wallet.can_sign(self.tx) or bool(self.main_window.tx_external_keypairs)))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/electroncash/wallet.py", line 3167, in can_sign
    _, addr = xpubkey_to_address(x_pubkey)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/electroncash/keystore.py", line 711, in xpubkey_to_address
    raise BaseException("Cannot parse pubkey")
BaseException: Cannot parse pubkey
```

# Example unsigned transaction (testnet4):
02000000029cbec37a535a9f0290d01d6230fb89cbf3da1ff9c282dcd623956218d6bc20ed00000000020151fefffffff68fd6eecb9974310547223c5ab8b288257825c48bc2a30489bd870ea9ea57ad010000001d01ff1afd76a914dff80da571817f2828a80d898f3596aed215091188acfeffffff545a6d29010000000160ee052a010000001976a914dff80da571817f2828a80d898f3596aed215091188ac00000000

# Additional information
* Electron Cash version: 4.4.1 
* Python version: 3.12.7 (main, Oct 1 2024, 11:15:50) [GCC 14.2.1 20240910] 
* Operating system: Linux-6.11.6-arch1-1-x86_64-with-glibc2.40 
* Wallet type: standard 
* Locale: C

**Comment by emergent-reasons** [comment]
To be more broad, it seems that `parse_scriptSig()` doesn't even attempt to parse p2sh20 or p2sh32 unless it's a p2sh multisig. And I assume those work because this part of the code is able to get the address from the xpub.

But even if it ignores this error, the rest of the code doesn't seem to know how to extract general p2sh.

Not sure why Electron chokes on p2sh inputs in the export process, and not in general parsing elsewhere. Must be using different code paths or different preparation of data?

**Comment by cculianu** [comment]
Yeah that function uses heuristics from the scriptSig to "guess" what the address "may have been". The problem is really that without seeing the previous txn's output (spent coin), this heuristic guessing mechanism basically fails often, especially for newer contracts that are p2sh non-multisig. So many new coins on chain now are non-multisih p2sh, that it will almost always fail. As the OP said initially, if there is only 1 push in the scritpSig, it guesses wrong and thinks it's p2pk. :(

Here are the heuristics it uses:

- If I see 1 push, I am "guessing" p2pk
- If I see 2 pushes, I am "guessing" p2pkh
- If I see a "0" pushed, and then a bunch of other pushes, I am "guessing" M-of-N multisig
- Otherwise, I give up

The heuristic check is failing on many cases now for non-multisig p2sh.. :(


I will try and plug this bug now.. it shouldn't be crashing at least...

**Comment by cculianu** [comment]
Ok, I fixed this, finally, by just handling the exception. TX opens now on latest master. Sorry for the late fix but thank you @defunct-operator for reporting this.
