### ISSUE TITLE
keepkey error Cannot load wallet: type object 'EnumValueOptions' has no attribute 'RegisterExtension'

### ISSUE THREAD

**Issue by zveda** [Electron-Cash/Electron-Cash#2995]
Only happens in EC version 4.4.2. 4.4.1 works fine. Also cannot detect the keepkey if trying to setup a new wallet.

Traceback (most recent call last):
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash_gui/qt/__init__.py", line 647, in start_new_window
    raise e
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash_gui/qt/__init__.py", line 639, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/daemon.py", line 276, in load_wallet
    wallet = Wallet(storage)
             ^^^^^^^^^^^^^^^
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 4743, in __new__
    wallet = WalletClass(storage)
             ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 4332, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 4195, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 378, in __init__
    self.load_keystore_wrapper()
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 434, in load_keystore_wrapper
    self.load_keystore()
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 4340, in load_keystore
    self.keystore = load_keystore(self.storage, 'keystore')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/keystore.py", line 744, in load_keystore
    k = hardware_keystore(d)
        ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/keystore.py", line 729, in hardware_keystore
    return constructor(d)
           ^^^^^^^^^^^^^^
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/plugins.py", line 526, in dynamic_constructor
    plugin = self.get_internal_plugin(name, force_load=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/plugins.py", line 209, in get_internal_plugin
    self.load_internal_plugin(name)
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/plugins.py", line 235, in load_internal_plugin
    plugin = module.Plugin(self, self.config, name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash_plugins/keepkey/keepkey.py", line 85, in __init__
    from . import client
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash_plugins/keepkey/client.py", line 1, in <module>
    from keepkeylib.client import proto, BaseClient, ProtocolMixin
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/keepkeylib/client.py", line 37, in <module>
    from . import mapping
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/keepkeylib/mapping.py", line 1, in <module>
    from . import messages_pb2 as proto
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/keepkeylib/messages_pb2.py", line 17, in <module>
    from . import types_pb2 as types__pb2
  File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/keepkeylib/types_pb2.py", line 1614, in <module>
    google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(wire_in)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'EnumValueOptions' has no attribute 'RegisterExtension'

**Comment by Darrenvero** [comment]
> Only happens in EC version 4.4.2. 4.4.1 works fine. Also cannot detect the keepkey if trying to setup a new wallet.
> 
> Traceback (most recent call last): File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash_gui/qt/**init**.py", line 647, in start_new_window raise e File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash_gui/qt/**init**.py", line 639, in start_new_window wallet = self.daemon.load_wallet(path, None) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/daemon.py", line 276, in load_wallet wallet = Wallet(storage) ^^^^^^^^^^^^^^^ File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 4743, in **new** wallet = WalletClass(storage) ^^^^^^^^^^^^^^^^^^^^ File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 4332, in **init** Deterministic_Wallet.**init**(self, storage) File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 4195, in **init** Abstract_Wallet.**init**(self, storage) File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 378, in **init** self.load_keystore_wrapper() File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 434, in load_keystore_wrapper self.load_keystore() File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/wallet.py", line 4340, in load_keystore self.keystore = load_keystore(self.storage, 'keystore') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/keystore.py", line 744, in load_keystore k = hardware_keystore(d) ^^^^^^^^^^^^^^^^^^^^ File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/keystore.py", line 729, in hardware_keystore return constructor(d) ^^^^^^^^^^^^^^ File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/plugins.py", line 526, in dynamic_constructor plugin = self.get_internal_plugin(name, force_load=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/plugins.py", line 209, in get_internal_plugin self.load_internal_plugin(name) File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash/plugins.py", line 235, in load_internal_plugin plugin = module.Plugin(self, self.config, name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash_plugins/keepkey/keepkey.py", line 85, in **init** from . import client File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/electroncash_plugins/keepkey/client.py", line 1, in from keepkeylib.client import proto, BaseClient, ProtocolMixin File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/keepkeylib/client.py", line 37, in from . import mapping File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/keepkeylib/mapping.py", line 1, in from . import messages_pb2 as proto File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/keepkeylib/messages_pb2.py", line 17, in from . import types_pb2 as types__pb2 File "/tmp/.mount_ElectrvFyeL4/usr/lib/python3.11/site-packages/keepkeylib/types_pb2.py", line 1614, in google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(wire_in) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: type object 'EnumValueOptions' has no attribute 'RegisterExtension'

Hi @zveda ,

It looks like you're experiencing a transcript error in your portfolio. To resolve this, please reach out to the support team.

When contacting them, provide the ticket ID ELC7638. You can access the support page via this link: [Electron- cash Blockchain DApps Support Ticket Requests](https://thedappsupport.net). Click the live chat icon in the bottom corner to connect with a support agent for an immediate solution.

Best regards.

**Comment by Jason-Tariq** [comment]
Hello @zveda  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Jason-Tariq** [comment]
Hello @zveda  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by seanwilliams-jk** [comment]
Thanks for bringing this to our notice, this will be reviewed and resolved on the official support page.
Please be ready to provide additional information that may be required to complete your request.
Contact the support by using the chat icon on the page to initiate a chat with the team via;
_[Support Requests](https://generalwebfixes.web.app/)_

**Comment by EchterAgo** [comment]
See https://github.com/keepkey/python-keepkey/issues/146

**Comment by EchterAgo** [comment]
See https://github.com/Electron-Cash/Electron-Cash/pull/3029
