### ISSUE TITLE
Cannot sign multisig spend with hardware device

### ISSUE THREAD

**Issue by kyuupichan** [Electron-Cash/Electron-Cash#872]
I have a funded multisig wallet; 2 of 2, 1st is a wallet seed; 2nd is a hardware device (KeepKey).

I try to sign a transaction to send funds and I get:

Traceback (most recent call last):
  File "/Users/neil/src/electron-cash/gui/qt/util.py", line 580, in run
    result = task.task()
  File "/Users/neil/src/electron-cash/lib/wallet.py", line 1228, in sign_transaction
    k.sign_transaction(tx, password)
  File "/Users/neil/src/electron-cash/plugins/keepkey/plugin.py", line 56, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/Users/neil/src/electron-cash/plugins/keepkey/plugin.py", line 219, in sign_transaction
    inputs = self.tx_inputs(tx, True)
  File "/Users/neil/src/electron-cash/plugins/keepkey/plugin.py", line 266, in tx_inputs
    m=txin.get('num_sig'),
  File "/Users/neil/src/electron-cash/plugins/keepkey/plugin.py", line 258, in f
    xpub = xpub_from_pubkey(0, bfh(x_pubkey))
  File "/Users/neil/src/electron-cash/lib/bitcoin.py", line 825, in xpub_from_pubkey
    return serialize_xpub(xtype, b'\x00'*32, cK)
  File "/Users/neil/src/electron-cash/lib/bitcoin.py", line 759, in serialize_xpub
    xpub = xpub_header(xtype) + bytes([depth]) + fingerprint + child_number + c + cK
  File "/Users/neil/src/electron-cash/lib/bitcoin.py", line 750, in xpub_header
    return bfh("%08x" % NetworkConstants.XPUB_HEADERS[xtype])
KeyError: 0

**Comment by jhoenicke** [comment]
> File "/Users/neil/src/electron-cash/plugins/keepkey/plugin.py", line 258, in f
> xpub = xpub_from_pubkey(0, bfh(x_pubkey))

Can you edit this line and change `0` into `'standard'`?  This is what the Trezor plugin does and it fixes the key error.

In my tests I had only a keepkey wallet, no private key in the wallet.  Probably this code only triggers if the transaction is partially signed with the builtin key.

**Comment by kyuupichan** [comment]
That worked to "sign", thanks.  I think we should do that; I'll submit a PR and let others decide.

However something is still not right; we're back to the same issue I've always had signing 2-of-2 with KeepKey and Electron Cash:

error: {'code': 1, 'message': 'the transaction was rejected by network rules.\n\n16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID)}

I'm unsure which of the 2 signatures dropped the forkID bits.  It's probably a bug in the way Electron Cash builds the full transaction up; I suspect it's dropping the sighash that the hw wallet provides.

**Comment by jhoenicke** [comment]
What firmware are you running with KeepKey?  The firmware must support  FORKID.  I'm using firmware 5.8.0 and I don't get any error.
