### ISSUE TITLE
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'Testing crash reports'

### ISSUE THREAD

**Issue by DrSpengler** [Electron-Cash/Electron-Cash#899]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.<lambda>(<console>:1)
	at <python>.run(stdlib/threading.py:864)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash_gui/android/daemon.py:39)
	at <python>.reraise(/android_asset/chaquopy/requirements-common.zip/six.py:693)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash_gui/android/daemon.py:30)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:274)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:246)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
	at $Proxy4.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
com.chaquo.python.PyException: ValueError: invalid literal for int() with base 10: 'Testing crash reports'
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.1-3  | 3.6.5 (default, Aug 20 2018, 13:13:33)  [GCC 5.3 20151204] | Android 8.0.0 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 
| 3.3.1-3  | 3.6.5 (default, Aug 20 2018, 13:13:33)  [GCC 5.3 20151204] | Android 8.0.0 on Google Android SDK built for x86 (generic_x86) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Testing complete, please close this issue.

**Comment by mhsmith** [comment]
Please close this issue: it was just a test of the crash report system.

**Comment by cculianu** [comment]
Done.
