### ISSUE TITLE
java.lang.RuntimeException: Unable to resume activity {org.electroncash.electroncash3/org.electroncash.electroncash3.MainActivity}: java.lang.RuntimeException: Cannot create an instance of class org.electroncash.electroncash3.DaemonModel

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#946]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3468)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3499)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.access$1200(ActivityThread.java:186)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5931)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
Caused by: java.lang.RuntimeException: Cannot create an instance of class org.electroncash.electroncash3.DaemonModel
	at android.arch.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:207)
	at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:134)
	at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:102)
	at org.electroncash.electroncash3.MainActivity$daemonModel$2.invoke(Main.kt:27)
	at org.electroncash.electroncash3.MainActivity$daemonModel$2.invoke(Main.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.electroncash.electroncash3.MainActivity.getDaemonModel(Main.kt)
	at org.electroncash.electroncash3.MainKt.getDaemonModel(Main.kt:93)
	at org.electroncash.electroncash3.WalletsFragment.onCreate(Wallets.kt:34)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
	at android.app.Activity.performResume(Activity.java:6250)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3453)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.arch.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:199)
	... 35 more
Caused by: com.chaquo.python.PyException: Exception: Daemon already running
	at <python>.__init__(/android_asset/chaquopy/app.zip/electroncash_gui/android/console.py:74)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:274)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:246)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:140)
	at org.electroncash.electroncash3.DaemonModel.<init>(Daemon.kt:30)
	... 38 more
java.lang.RuntimeException: Unable to resume activity {org.electroncash.electroncash3/org.electroncash.electroncash3.MainActivity}: java.lang.RuntimeException: Cannot create an instance of class org.electroncash.electroncash3.DaemonModel
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.1-4  | 3.6.5 (default, Aug 20 2018, 13:16:15)  [GCC 5.3 20151204] | Android 5.1 on HUAWEI HUAWEI CUN-L21 (HWCUN-L6735) | unknown | en_US | 
| 3.3.1-4  | 3.6.5 (default, Aug 20 2018, 13:16:15)  [GCC 5.3 20151204] | Android 5.1 on HUAWEI HUAWEI CUN-L21 (HWCUN-L6735) | unknown | en_US | 

Additional Information
------------------------

> Calin here
> 
> I hit the home key while.in the console screen

---

**Comment by mhsmith** [comment]
This has been fixed in the newer versions: please close the issue.

**Comment by cculianu** [comment]
You got it, boss.
