### ISSUE TITLE
during chain switch synchronization: "RuntimeError: dictionary changed size during iteration"

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#956]
this is on f6bff0b9216d13ac8144c9e3f2c4222a59ac454a
got this while switching chains:

```
Traceback (most recent call last):
  File "/home/nick/bitcoin/electron-cash/lib/util.py", line 153, in run_jobs
    job.run()
  File "/home/nick/bitcoin/electron-cash/lib/verifier.py", line 52, in run
    for tx_hash, tx_height in unverified.items():
RuntimeError: dictionary changed size during iteration
```

probably some block came in during synchronization?

**Comment by cculianu** [comment]
This is due to a race condition in the wallet code and the verifier code. UGH.  Fixing now.
