### ISSUE TITLE
Doesn't work with Ledger on Ubuntu 18.04

### ISSUE THREAD

**Issue by dskloet** [Electron-Cash/Electron-Cash#967]
First I followed the instructions [here](https://webcache.googleusercontent.com/search?q=cache:q0wZK3cD0-0J:https://support.ledgerwallet.com/hc/en-us/articles/360009676633-Set-up-and-use-Electron-Cash+&cd=1&hl=en&ct=clnk&gl=ch).
After choosing "Use a hardware device", Electron Cash just said no hardware wallet was found.
Then I followed the instructions [here](https://www.reddit.com/r/btc/comments/7o8wxf/electron_cash_now_supports_the_ledger_nano_s/dtmeoha/).
And now Electron Cash is completely broken on my computer :-(

Please help?

    $ ./electron-cash
    Traceback (most recent call last):
      File "./electron-cash", line 87, in <module>
        check_imports()
      File "./electron-cash", line 72, in check_imports
        import google.protobuf
      File "/home/dskloet/ElectronCash/Electron Cash-3.3.2/packages/google/protobuf/__init__.py", line 37, in <module>
        __import__('pkg_resources').declare_namespace(__name__)
      File "/home/dskloet/ElectronCash/Electron Cash-3.3.2/packages/pkg_resources/__init__.py", line 3126, in <module>
        @_call_aside
      File "/home/dskloet/ElectronCash/Electron Cash-3.3.2/packages/pkg_resources/__init__.py", line 3110, in _call_aside
        f(*args, **kwargs)
      File "/home/dskloet/ElectronCash/Electron Cash-3.3.2/packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/home/dskloet/ElectronCash/Electron Cash-3.3.2/packages/pkg_resources/__init__.py", line 572, in _build_master
        ws = cls()
      File "/home/dskloet/ElectronCash/Electron Cash-3.3.2/packages/pkg_resources/__init__.py", line 565, in __init__
        self.add_entry(entry)
      File "/home/dskloet/ElectronCash/Electron Cash-3.3.2/packages/pkg_resources/__init__.py", line 621, in add_entry
        for dist in find_distributions(entry, True):
      File "/home/dskloet/ElectronCash/Electron Cash-3.3.2/packages/pkg_resources/__init__.py", line 1968, in find_on_path
        for dist in factory(fullpath):
      File "/home/dskloet/ElectronCash/Electron Cash-3.3.2/packages/pkg_resources/__init__.py", line 2030, in distributions_from_metadata
        if len(os.listdir(path)) == 0:
    PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/hidapi-0.7.99.post21.egg-info'

**Comment by dskloet** [comment]
I fixed (?) the crash with

    $ sudo pip3 uninstall hidapi

Now I'm back at "No hardware device detected."
I tried rebooting and not starting anything but Electron Cash to make sure nothing else is holding a lock on my Ledger Nano S. But that didn't work either. I can use the Ledger app so my udev rules must be correct.

**Comment by dskloet** [comment]
If I run with --verbose I get

```
[Plugins] loaded internal plugin digitalbitbox
[Plugins] loaded internal plugin keepkey
[Plugins] loaded internal plugin ledger
[Plugins] loaded internal plugin trezor
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[94.1.159.183] failed to connect timed out
[bch.curalle.ovh] connected
[bch.curalle.ovh] set_mode(default)
```

**Comment by dskloet** [comment]
I tried installing btchip-python without sudo. After it at least gives an error for ledger instead of scanning without result

```
[Plugins] loaded internal plugin digitalbitbox
[Plugins] loaded internal plugin keepkey
[Plugins] loaded internal plugin ledger
[Plugins] loaded internal plugin trezor
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] error keepkey
[DeviceMgr] scanning devices...
[DeviceMgr] error ledger
[DeviceMgr] scanning devices...
[DeviceMgr] error trezor
```

**Comment by dskloet** [comment]
If I run with

```sudo ./electron-cash```

it works. But I'd rather not run it as root. Any idea how I can run in user space?

**Comment by jhoenicke** [comment]
You need to install udev rules: https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh

**Comment by dskloet** [comment]
Are those rules specific to Electron Cash? I'm already able to use the Ledger app so I thought my udev rules are sufficient?

**Comment by dskloet** [comment]
It worked, but I don't understand why since those rules come from Ledger and don't seem to have anything to do with Electron Cash specifically and my Ledger already worked with the Ledger app before.

**Comment by jhoenicke** [comment]
Normally you need to install the udev rules to use the Ledger app, at least it was the case in the past.  Maybe they found another work around or the chrome app runs with root permissions.

**Comment by cculianu** [comment]
Disclaimer: I'm a ledger luddite.

This seems not related to Electron Cash and solved. Closing.
